// packages/solid/src/DefaultSolutionModal.tsx
import type * as srk from '@algoux/standard-ranklist';
import {
  formatSolutionTimestamp,
  getSolutionModalTitle,
  getSolutionResultMeta,
} from '@algoux/standard-ranklist-renderer-component-core';
import { createEffect, createSignal, For, Show } from 'solid-js';
import { Modal, type ModalProps } from './Modal';

export interface DefaultSolutionModalProps
  extends Pick<ModalProps, 'open' | 'onClose' | 'rootClassName' | 'wrapClassName' | 'style'> {
  user?: srk.User | null;
  problem?: srk.Problem;
  problemIndex: number;
  solutions: srk.Solution[];
  title?: string;
  width?: number;
}

export function DefaultSolutionModal(props: DefaultSolutionModalProps) {
  const [cachedPayload, setCachedPayload] = createSignal<{
    user: srk.User;
    problem?: srk.Problem;
    problemIndex: number;
    solutions: srk.Solution[];
  } | null>(
    props.user
      ? {
          user: props.user,
          problem: props.problem,
          problemIndex: props.problemIndex,
          solutions: props.solutions || [],
        }
      : null,
  );

  createEffect(() => {
    if (props.user) {
      setCachedPayload({
        user: props.user,
        problem: props.problem,
        problemIndex: props.problemIndex,
        solutions: props.solutions || [],
      });
    }
  });

  return (
    <Show when={cachedPayload()}>
      {(payload) => (
        <Modal
          open={props.open}
          onClose={props.onClose}
          rootClassName={props.rootClassName || 'srk-general-modal-root'}
          style={props.style}
          title={props.title || getSolutionModalTitle(payload().problemIndex, payload().user)}
          width={props.width || 320}
          wrapClassName={props.wrapClassName || 'srk-solutions-modal'}
        >
          <table class="srk-common-table srk-solutions-table">
            <thead>
              <tr>
                <th class="srk--text-left">Result</th>
                <th class="srk--text-right">Time</th>
              </tr>
            </thead>
            <tbody>
              <For each={payload().solutions}>
                {(solution) => {
                  const meta = () => getSolutionResultMeta(solution.result);
                  return (
                    <tr>
                      <td>
                        <span class={`srk-solution-result-text ${meta().className || ''}`}>{meta().label}</span>
                      </td>
                      <td class="srk--text-right">{formatSolutionTimestamp(solution)}</td>
                    </tr>
                  );
                }}
              </For>
            </tbody>
          </table>
        </Modal>
      )}
    </Show>
  );
}

// packages/svelte/src/DefaultSolutionModal.svelte
<script>
  import {
    formatSolutionTimestamp,
    getSolutionModalTitle,
    getSolutionResultMeta,
  } from '@algoux/standard-ranklist-renderer-component-core';
  import { createEventDispatcher } from 'svelte';
  import Modal from './Modal.svelte';

  export let open = false;
  export let user = null;
  export let problem = undefined;
  export let problemIndex = 0;
  export let solutions = [];
  export let title = undefined;
  export let width = 320;
  export let rootClassName = 'srk-general-modal-root';
  export let wrapClassName = 'srk-solutions-modal';
  export let style = {};
  let cachedPayload = user
    ? {
        user,
        problem,
        problemIndex,
        solutions,
      }
    : null;

  const dispatch = createEventDispatcher();

  $: if (user) {
    cachedPayload = {
      user,
      problem,
      problemIndex,
      solutions,
    };
  }

  $: resolvedTitle = title || (cachedPayload ? getSolutionModalTitle(cachedPayload.problemIndex, cachedPayload.user) : '');
</script>

{#if cachedPayload}
  <Modal
    {open}
    title={resolvedTitle}
    {width}
    {rootClassName}
    {wrapClassName}
    {style}
    on:close={(event) => dispatch('close', event.detail)}
  >
    <table class="srk-common-table srk-solutions-table" aria-label={problem && problem.alias ? `Solutions for ${problem.alias}` : undefined}>
      <thead>
        <tr>
          <th class="srk--text-left">Result</th>
          <th class="srk--text-right">Time</th>
        </tr>
      </thead>
      <tbody>
        {#each cachedPayload.solutions as solution, index (`${solution.result}_${solution.time && solution.time[0]}_${index}`)}
          {@const meta = getSolutionResultMeta(solution.result)}
          <tr>
            <td>
              <span class={`srk-solution-result-text ${meta.className || ''}`}>
                {meta.label}
              </span>
            </td>
            <td class="srk--text-right">{formatSolutionTimestamp(solution)}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </Modal>
{/if}
