// packages/angular/src/lib/modal/default-solution-modal.component.ts
import type * as srk from '@algoux/standard-ranklist';
import { CommonModule } from '@angular/common';
import {
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
} from '@angular/core';
import {
  formatSolutionTimestamp,
  getSolutionModalTitle,
  getSolutionResultMeta,
  type SolutionResultMeta,
} from '../ranklist/ranklist-utils';
import {
  ModalComponent,
  type ModalCloseReason,
} from './modal.component';

@Component({
  selector: 'srk-default-solution-modal',
  standalone: true,
  imports: [CommonModule, ModalComponent],
  template: `
    <srk-modal
      *ngIf="cachedUser"
      [open]="open"
      [title]="resolvedTitle()"
      [width]="width"
      [rootClassName]="rootClassName"
      [wrapClassName]="wrapClassName"
      [panelStyle]="panelStyle"
      (close)="close.emit($event)"
      (openChange)="openChange.emit($event)"
    >
      <table class="srk-common-table srk-solutions-table">
        <thead>
          <tr>
            <th class="srk--text-left">Result</th>
            <th class="srk--text-right">Time</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let solution of cachedSolutions; let index = index; trackBy: trackBySolution">
            <td>
              <span
                class="srk-solution-result-text"
                [ngClass]="solutionMeta(solution).className"
              >
                {{ solutionMeta(solution).label }}
              </span>
            </td>
            <td class="srk--text-right">{{ formatSolutionTimestamp(solution) }}</td>
          </tr>
        </tbody>
      </table>
    </srk-modal>
  `,
})
export class DefaultSolutionModalComponent implements OnChanges {
  @Input() open = false;
  @Input() user?: srk.User | null;
  @Input() problem?: srk.Problem;
  @Input() problemIndex = 0;
  @Input() solutions: srk.Solution[] = [];
  @Input() title?: string;
  @Input() width = 320;
  @Input() rootClassName = 'srk-general-modal-root';
  @Input() wrapClassName = 'srk-solutions-modal';
  @Input() panelStyle: Record<string, string | number> = {};
  @Input() languages?: readonly string[];

  @Output() openChange = new EventEmitter<boolean>();
  @Output() close = new EventEmitter<ModalCloseReason>();

  readonly formatSolutionTimestamp = formatSolutionTimestamp;
  cachedUser: srk.User | null = null;
  cachedProblem?: srk.Problem;
  cachedProblemIndex = 0;
  cachedSolutions: srk.Solution[] = [];

  ngOnChanges(_changes: SimpleChanges) {
    if (this.user) {
      this.cachedUser = this.user;
      this.cachedProblem = this.problem;
      this.cachedProblemIndex = this.problemIndex;
      this.cachedSolutions = this.solutions;
    }
  }

  resolvedTitle() {
    return this.title || (this.cachedUser ? getSolutionModalTitle(this.cachedProblemIndex, this.cachedUser, this.languages) : '');
  }

  solutionMeta(solution: srk.Solution): SolutionResultMeta {
    return getSolutionResultMeta(solution.result);
  }

  trackBySolution(index: number, solution: srk.Solution) {
    return `${solution.result}_${solution.time?.[0]}_${index}`;
  }
}

// packages/svelte/src/DefaultSolutionModal.svelte
<script>
  import {
    formatSolutionTimestamp,
    getSolutionModalTitle,
    getSolutionResultMeta,
  } from '@algoux/standard-ranklist-renderer-component-core';
  import { createEventDispatcher } from 'svelte';
  import Modal from './Modal.svelte';

  export let open = false;
  export let user = null;
  export let problem = undefined;
  export let problemIndex = 0;
  export let solutions = [];
  export let title = undefined;
  export let width = 320;
  export let rootClassName = 'srk-general-modal-root';
  export let wrapClassName = 'srk-solutions-modal';
  export let style = {};
  export let languages = undefined;
  let cachedPayload = user
    ? {
        user,
        problem,
        problemIndex,
        solutions,
      }
    : null;

  const dispatch = createEventDispatcher();

  $: if (user) {
    cachedPayload = {
      user,
      problem,
      problemIndex,
      solutions,
    };
  }

  $: resolvedTitle = title || (cachedPayload ? getSolutionModalTitle(cachedPayload.problemIndex, cachedPayload.user, languages) : '');
</script>

{#if cachedPayload}
  <Modal
    {open}
    title={resolvedTitle}
    {width}
    {rootClassName}
    {wrapClassName}
    {style}
    on:close={(event) => dispatch('close', event.detail)}
  >
    <table class="srk-common-table srk-solutions-table" aria-label={problem && problem.alias ? `Solutions for ${problem.alias}` : undefined}>
      <thead>
        <tr>
          <th class="srk--text-left">Result</th>
          <th class="srk--text-right">Time</th>
        </tr>
      </thead>
      <tbody>
        {#each cachedPayload.solutions as solution, index (`${solution.result}_${solution.time && solution.time[0]}_${index}`)}
          {@const meta = getSolutionResultMeta(solution.result)}
          <tr>
            <td>
              <span class={`srk-solution-result-text ${meta.className || ''}`}>
                {meta.label}
              </span>
            </td>
            <td class="srk--text-right">{formatSolutionTimestamp(solution)}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </Modal>
{/if}
