// packages/angular/src/lib/ranklist/ranklist.component.ts
import type * as srk from '@algoux/standard-ranklist';
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  ContentChild,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';
import {
  EnumTheme,
  formatTimeDuration,
  numberToAlphabet,
  resolveStyle,
  resolveText,
  resolveUserMarkers,
} from '@algoux/standard-ranklist-utils';
import type { ThemeColor } from '@algoux/standard-ranklist-utils';
import {
  calculateDirtPercentage,
  calculateProblemStatisticsFooter,
  calculateSEValue,
  caniuse,
  formatProblemStatisticsAcceptedMinute,
  formatProblemStatisticsAverageHardness,
  formatProblemStatisticsPercent,
  getMarkerPresentation,
  getProblemHeaderBackgroundImage,
  getRankProblemStatusCellPresentation,
  resolveSrkAssetUrl,
  shouldShowTimeColumn,
  srkSupportedVersions,
} from '@algoux/standard-ranklist-renderer-component-core';
import type {
  ProblemStatisticsFooter,
  RanklistColumnTitles,
  RanklistStatusCellPreset,
  RanklistUserAvatarPlacement,
} from '@algoux/standard-ranklist-renderer-component-core';
import { captureModalTriggerPointFromMouseEvent } from '../modal/modal-interactions';
import type {
  RankValue,
  SolutionClickPayload,
  StaticRanklist,
  StaticRanklistRow,
  UserClickPayload,
} from '../types';
import {
  SrkStatusCellTemplateDirective,
  type StatusCellTemplateContext,
} from './status-cell-template.directive';
import {
  SrkUserCellTemplateDirective,
  type UserCellTemplateContext,
} from './user-cell-template.directive';

@Component({
  selector: 'srk-ranklist',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CommonModule],
  template: `
    <div *ngIf="data.type !== 'general'; else versionState">
      srk type "{{ data.type }}" is not supported
    </div>

    <ng-template #versionState>
      <div *ngIf="!isSupportedVersion(); else ranklistTable">
        srk version "{{ data.version }}" is not supported (current supported: {{ supportedVersions }})
      </div>
    </ng-template>

    <ng-template #ranklistTable>
      <div class="srk-common-table srk-main">
        <table
          [class.srk-table-row-bordered]="borderedRows || rowBordered"
          [class.srk-table-column-bordered]="columnBordered"
          [class.srk-table-row-striped]="stripedRows"
        >
          <thead>
            <tr>
              <th
                *ngFor="let seriesItem of data.series; let seriesIndex = index"
                class="srk-series-header srk--text-right srk--nowrap"
                [class.srk-series-segmented-column]="isSeriesSegmentedColumn(seriesItem)"
              >
                {{ resolveSeriesColumnTitle(seriesItem, seriesIndex) }}
              </th>
              <th
                *ngIf="splitOrganization"
                class="srk-organization-header srk--text-left srk--nowrap"
              >
                {{ resolveColumnTitle('organization', 'Organization') }}
              </th>
              <th class="srk--text-left srk--nowrap">{{ resolveColumnTitle('user', 'Name') }}</th>
              <th class="srk--text-right srk--nowrap">{{ resolveColumnTitle('score', 'Score') }}</th>
              <th *ngIf="showTimeColumn()" class="srk--text-right srk--nowrap">
                {{ resolveColumnTitle('time', 'Time') }}
              </th>
              <th
                *ngFor="let problem of data.problems; let problemIndex = index"
                class="srk--nowrap srk-problem-header"
                [style.background-image]="problemHeaderBackgroundImage(problem)"
              >
                <a
                  *ngIf="problem.link; else unlinkedProblemHeader"
                  [href]="problem.link"
                  target="_blank"
                  rel="noopener noreferrer"
                  style="color: unset"
                >
                  <span class="srk--display-block">{{ problemAlias(problem, problemIndex) }}</span>
                  <span
                    *ngIf="problem.statistics"
                    class="srk--display-block srk-problem-stats"
                    [title]="problemStatsTitle(problem.statistics)"
                  >
                    {{ problem.statistics.accepted }}
                  </span>
                </a>
                <ng-template #unlinkedProblemHeader>
                  <span class="srk--display-block">{{ problemAlias(problem, problemIndex) }}</span>
                  <span
                    *ngIf="problem.statistics"
                    class="srk--display-block srk-problem-stats"
                    [title]="problemStatsTitle(problem.statistics)"
                  >
                    {{ problem.statistics.accepted }}
                  </span>
                </ng-template>
              </th>
              <th *ngIf="showDirtColumn" class="srk-dirt-header srk--text-right srk--nowrap">
                {{ resolveColumnTitle('dirt', 'Dirt') }}
              </th>
              <th *ngIf="showSEColumn" class="srk-se-header srk--text-right srk--nowrap">
                {{ resolveColumnTitle('se', 'SE') }}
              </th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let row of data.rows; let rowIndex = index">
              <td
                *ngFor="let rankValue of getRankValues(row); let seriesIndex = index"
                class="srk--text-right srk--nowrap"
                [ngClass]="getSeriesSegmentClass(rankValue, data.series[seriesIndex])"
                [class.srk-series-segmented-column]="isSeriesSegmentedColumn(data.series[seriesIndex])"
                [ngStyle]="getSeriesSegmentStyle(rankValue, data.series[seriesIndex])"
              >
                {{ getRankText(rankValue, row) }}
              </td>

              <td
                *ngIf="splitOrganization"
                class="srk-organization-cell srk--text-left srk--nowrap"
                [class.srk-organization-cell-avatar]="showAvatarInOrganization() && !!row.user.avatar"
              >
                <div class="srk-organization-cell-content">
                  <div *ngIf="showAvatarInOrganization() && row.user.avatar" class="srk-user-avatar">
                    <img
                      [src]="formatAssetUrl(row.user.avatar, 'user.avatar')"
                      alt="User Avatar"
                    />
                  </div>
                  <span
                    class="srk-organization-name-text"
                    [title]="row.user.organization ? resolveDisplayText(row.user.organization) : ''"
                    [textContent]="row.user.organization ? resolveDisplayText(row.user.organization) : ''"
                  ></span>
                </div>
              </td>

              <ng-container *ngIf="userCellTemplate; else defaultUserCell">
                <ng-container
                  [ngTemplateOutlet]="userCellTemplate.templateRef"
                  [ngTemplateOutletContext]="buildUserCellContext(row, rowIndex)"
                />
              </ng-container>
              <ng-template #defaultUserCell>
                <td
                  class="srk--text-left srk--nowrap srk-user-cell srk--cursor-pointer"
                  role="button"
                  tabindex="0"
                  (click)="emitUserClick($event, row, rowIndex)"
                  (keydown.enter)="activateUserCellFromKeyboard($event, row, rowIndex)"
                  (keydown.space)="activateUserCellFromKeyboard($event, row, rowIndex)"
                >
                  <div class="srk-user-cell-content">
                    <div *ngIf="row.user.avatar && !showAvatarInOrganization()" class="srk-user-avatar">
                      <img
                        [src]="formatAssetUrl(row.user.avatar, 'user.avatar')"
                        alt="User Avatar"
                      />
                    </div>
                    <div class="srk-user-body">
                      <div class="srk-user-name-row">
                        <span
                          class="srk-user-name-text"
                          [title]="resolveDisplayText(row.user.name)"
                        >
                          {{ resolveDisplayText(row.user.name) }}
                        </span>
                        <span class="srk-marker-dot-group">
                          <span
                            *ngFor="let marker of resolvedUserMarkers(row.user)"
                            class="srk-marker srk-marker-dot srk--c-tooltip"
                            [ngClass]="marker.presentation.className"
                            [ngStyle]="marker.presentation.style"
                            [attr.data-tooltip]="resolveDisplayText(marker.marker.label)"
                          ></span>
                        </span>
                      </div>
                      <p
                        *ngIf="row.user.organization && !splitOrganization"
                        class="srk-user-secondary-text srk--text-ellipsis"
                        title=""
                      >
                        {{ resolveDisplayText(row.user.organization) }}
                      </p>
                    </div>
                  </div>
                </td>
              </ng-template>

              <td class="srk--text-right srk--nowrap">{{ row.score.value }}</td>
              <td *ngIf="showTimeColumn()" class="srk--text-right srk--nowrap">
                {{ row.score.time ? formatTime(row.score.time) : '-' }}
              </td>

              <ng-container *ngFor="let status of row.statuses; let problemIndex = index">
                <ng-container *ngIf="statusCellTemplate; else defaultStatusCell">
                  <ng-container
                    [ngTemplateOutlet]="statusCellTemplate.templateRef"
                    [ngTemplateOutletContext]="buildStatusCellContext(row, rowIndex, status, problemIndex)"
                  />
                </ng-container>
                <ng-template #defaultStatusCell>
                  <td
                    *ngIf="status.result === 'FB' || status.result === 'AC'; else failedOrFrozenStatus"
                    [ngClass]="statusCellClass(status)"
                    [attr.role]="statusCellRole(status)"
                    [attr.tabindex]="statusCellTabIndex(status)"
                    (click)="emitSolutionClick($event, row, rowIndex, status, problemIndex)"
                    (keydown.enter)="activateStatusCellFromKeyboard($event, row, rowIndex, status, problemIndex)"
                    (keydown.space)="activateStatusCellFromKeyboard($event, row, rowIndex, status, problemIndex)"
                  >
                    <span
                      *ngIf="statusColorAsText && status.result === 'FB'"
                      class="srk-prest-status-block-fb-star"
                      [textContent]="firstBloodStar"
                    ></span>
                    <ng-container *ngIf="statusPresentation(status) as presentation">
                      <ng-container *ngIf="isNumber(presentation.score); else statusText">
                        <span class="srk-prest-status-block-score">{{ presentation.score }}</span>
                        <span class="srk-prest-status-block-score-details">
                          {{ presentation.scoreDetails }}
                        </span>
                      </ng-container>
                      <ng-template #statusText>
                        <ng-container *ngIf="presentation.secondary !== undefined; else singleStatus">
                          <span class="srk-prest-status-block-primary">{{ presentation.primary || '' }}</span>
                          <span [textContent]="statusSeparator"></span>
                          <span class="srk-prest-status-block-secondary">{{ presentation.secondary }}</span>
                        </ng-container>
                        <ng-template #singleStatus>{{ presentation.primary }}</ng-template>
                      </ng-template>
                    </ng-container>
                  </td>
                  <ng-template #failedOrFrozenStatus>
                    <td
                      *ngIf="status.result === '?' || status.result === 'RJ'; else emptyStatus"
                      [ngClass]="statusCellClass(status)"
                      [attr.role]="statusCellRole(status)"
                      [attr.tabindex]="statusCellTabIndex(status)"
                      (click)="emitSolutionClick($event, row, rowIndex, status, problemIndex)"
                      (keydown.enter)="activateStatusCellFromKeyboard($event, row, rowIndex, status, problemIndex)"
                      (keydown.space)="activateStatusCellFromKeyboard($event, row, rowIndex, status, problemIndex)"
                    >
                      <ng-container *ngIf="statusPresentation(status) as presentation">
                        <ng-container *ngIf="presentation.secondary !== undefined; else singleStatus">
                          <span class="srk-prest-status-block-primary">{{ presentation.primary || '' }}</span>
                          <span [textContent]="statusSeparator"></span>
                          <span class="srk-prest-status-block-secondary">{{ presentation.secondary }}</span>
                        </ng-container>
                        <ng-template #singleStatus>{{ presentation.primary }}</ng-template>
                      </ng-container>
                    </td>
                  </ng-template>
                  <ng-template #emptyStatus>
                    <td class="srk-status-placeholder-cell srk--text-center srk--nowrap">
                      {{ emptyStatusPlaceholder }}
                    </td>
                  </ng-template>
                </ng-template>
              </ng-container>

              <td *ngIf="showDirtColumn" class="srk-dirt-cell srk--text-right srk--nowrap">
                {{ calculateDirtPercentage(row) }}
              </td>
              <td *ngIf="showSEColumn" class="srk-se-cell srk--text-right srk--nowrap">
                {{ calculateSEValue(row, problemStatistics) }}
              </td>
            </tr>
          </tbody>
          <tfoot *ngIf="showProblemStatisticsFooter">
            <tr
              *ngFor="let footerRow of problemStatisticsFooterRows"
              class="srk-problem-statistics-footer-row"
            >
              <td
                class="srk-problem-statistics-footer-labels srk--text-right srk--nowrap"
                [attr.colspan]="leftFooterColumnCount()"
              >
                <span
                  class="srk-problem-statistics-footer-label srk--c-tooltip"
                  [attr.data-tooltip]="footerRow.tooltip"
                >
                  {{ footerRow.label }}
                </span>
              </td>
              <td
                *ngFor="let stat of problemStatistics"
                class="srk-problem-statistics-footer-cell srk--text-center srk--nowrap"
              >
                <span class="srk-problem-statistics-footer-primary">
                  {{ getProblemStatisticsFooterCellPrimary(footerRow.key, stat) }}
                </span>
                <ng-container *ngIf="getProblemStatisticsFooterCellSecondary(footerRow.key, stat) !== undefined">
                  <span> </span>
                  <span class="srk-problem-statistics-footer-secondary">
                    {{ getProblemStatisticsFooterCellSecondary(footerRow.key, stat) }}
                  </span>
                </ng-container>
              </td>
              <td
                *ngIf="showDirtColumn"
                class="srk-problem-statistics-footer-cell srk-extra-statistics-footer-cell srk-dirt-footer-cell srk--nowrap"
              >
                <span class="srk-problem-statistics-footer-primary"></span>
              </td>
              <td
                *ngIf="showSEColumn"
                class="srk-problem-statistics-footer-cell srk-extra-statistics-footer-cell srk-se-footer-cell srk--nowrap"
              >
                <span class="srk-problem-statistics-footer-primary"></span>
              </td>
            </tr>
            <tr class="srk-problem-statistics-footer-row srk-problem-statistics-footer-problem-label-row">
              <td
                class="srk-problem-statistics-footer-labels srk--text-right srk--nowrap"
                [attr.colspan]="leftFooterColumnCount()"
              ></td>
              <td
                *ngFor="let problem of data.problems; let problemIndex = index"
                class="srk-problem-statistics-footer-cell srk-problem-statistics-footer-problem-header srk-problem-header srk--text-center srk--nowrap"
                [style.background-image]="problemHeaderBackgroundImage(problem, 0)"
              >
                <span class="srk--display-block">{{ problemAlias(problem, problemIndex) }}</span>
              </td>
              <td
                *ngIf="showDirtColumn"
                class="srk-problem-statistics-footer-cell srk-extra-statistics-footer-cell srk-dirt-footer-cell srk--nowrap"
              >
                <span class="srk-problem-statistics-footer-primary"></span>
              </td>
              <td
                *ngIf="showSEColumn"
                class="srk-problem-statistics-footer-cell srk-extra-statistics-footer-cell srk-se-footer-cell srk--nowrap"
              >
                <span class="srk-problem-statistics-footer-primary"></span>
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
    </ng-template>
  `,
})
export class RanklistComponent {
  @Input({ required: true }) data!: StaticRanklist;
  @Input() theme: EnumTheme = EnumTheme.light;
  @Input() borderedRows = false;
  @Input() rowBordered = false;
  @Input() columnBordered = false;
  @Input() stripedRows = false;
  @Input() formatSrkAssetUrl?: (url: string, field: string) => string;
  @Input() splitOrganization = false;
  @Input() columnTitles?: RanklistColumnTitles;
  @Input() statusCellPreset: RanklistStatusCellPreset = 'classic';
  @Input() statusColorAsText = false;
  @Input() showProblemStatisticsFooter = false;
  @Input() showDirtColumn = false;
  @Input() showSEColumn = false;
  @Input() emptyStatusPlaceholder: string | null = null;
  @Input() userAvatarPlacement: RanklistUserAvatarPlacement = 'user';

  @Output() userClick = new EventEmitter<UserClickPayload>();
  @Output() solutionClick = new EventEmitter<SolutionClickPayload>();

  @ContentChild(SrkStatusCellTemplateDirective)
  statusCellTemplate?: SrkStatusCellTemplateDirective;

  @ContentChild(SrkUserCellTemplateDirective)
  userCellTemplate?: SrkUserCellTemplateDirective;

  readonly supportedVersions = srkSupportedVersions;
  readonly firstBloodStar = '\u2605';
  readonly statusSeparator = ' ';
  readonly problemStatisticsFooterRows = [
    {
      key: 'accepted',
      label: 'Accepted',
      tooltip: 'Number of participants who solved this problem',
    },
    {
      key: 'tried',
      label: 'Tried',
      tooltip: 'Number of participants who attempted this problem',
    },
    {
      key: 'submitted',
      label: 'Submitted',
      tooltip: 'Total number of valid submissions for this problem',
    },
    {
      key: 'dirt',
      label: 'Dirt',
      tooltip: 'Wrong submissions among participants who solved this problem',
    },
    {
      key: 'se',
      label: 'SE',
      tooltip: 'Average hardness, calculated as (participants - accepted) / participants',
    },
    {
      key: 'firstAccepted',
      label: 'FB at',
      tooltip: 'First Blood at, also known as first solve time, in minutes',
    },
    {
      key: 'lastAccepted',
      label: 'LB at',
      tooltip: 'Last Blood at, also known as last solve time, in minutes',
    },
  ];
  private problemStatisticsSource?: StaticRanklist;
  private problemStatisticsCache?: ProblemStatisticsFooter[];

  get problemStatistics() {
    if (!this.showProblemStatisticsFooter && !this.showSEColumn) {
      return [];
    }
    if (this.problemStatisticsSource !== this.data || !this.problemStatisticsCache) {
      this.problemStatisticsSource = this.data;
      this.problemStatisticsCache = calculateProblemStatisticsFooter(this.data);
    }
    return this.problemStatisticsCache;
  }

  isSupportedVersion() {
    return caniuse(this.data.version);
  }

  showTimeColumn() {
    return shouldShowTimeColumn(this.data.rows);
  }

  showAvatarInOrganization() {
    return this.splitOrganization && this.userAvatarPlacement === 'organization';
  }

  leftFooterColumnCount() {
    return this.data.series.length + 1 + 1 + (this.showTimeColumn() ? 1 : 0) + (this.splitOrganization ? 1 : 0);
  }

  getRankValues(row: StaticRanklistRow): RankValue[] {
    return row.rankValues || this.data.series.map(() => ({ rank: null, segmentIndex: null }));
  }

  getRankText(rankValue: RankValue, row: StaticRanklistRow) {
    return rankValue.rank ? rankValue.rank : row.user.official === false ? '＊' : '';
  }

  resolveDisplayText(text: Parameters<typeof resolveText>[0]) {
    return resolveText(text);
  }

  resolveSeriesColumnTitle(series: srk.RankSeries, index: number) {
    const seriesTitles = this.columnTitles?.series;
    if (typeof seriesTitles === 'function') {
      return seriesTitles(series, index) ?? series.title;
    }
    if (Array.isArray(seriesTitles)) {
      return seriesTitles[index] ?? series.title;
    }
    return series.title;
  }

  resolveColumnTitle(key: Exclude<keyof RanklistColumnTitles, 'series'>, fallback: string) {
    return this.columnTitles?.[key] ?? fallback;
  }

  problemAlias(problem: srk.Problem, problemIndex: number) {
    return problem.alias || numberToAlphabet(problemIndex);
  }

  problemStatsTitle(statistics: srk.ProblemStatistics) {
    const ratio = statistics.submitted ? ((statistics.accepted / statistics.submitted) * 100).toFixed(1) : 0;
    return `${statistics.accepted} / ${statistics.submitted} (${ratio}%)`;
  }

  problemHeaderBackgroundImage(problem: srk.Problem, gradientDirection = 180) {
    return getProblemHeaderBackgroundImage(problem.style, this.theme, gradientDirection);
  }

  resolvedUserMarkers(user: srk.User) {
    return resolveUserMarkers(user, this.data.markers).map((marker) => ({
      marker,
      presentation: getMarkerPresentation(marker, this.theme),
    }));
  }

  formatAssetUrl(url: string, field: string) {
    return resolveSrkAssetUrl(url, field, this.formatSrkAssetUrl);
  }

  formatTime(time: Parameters<typeof formatTimeDuration>[0]) {
    return formatTimeDuration(time, 'min', Math.floor);
  }

  calculateDirtPercentage(row: StaticRanklistRow) {
    return calculateDirtPercentage(row);
  }

  calculateSEValue(row: StaticRanklistRow, problemStatistics: ProblemStatisticsFooter[]) {
    return calculateSEValue(row, problemStatistics);
  }

  statusPresentation(status: srk.RankProblemStatus) {
    return getRankProblemStatusCellPresentation(status, this.data, this.statusCellPreset);
  }

  isNumber(value: unknown): value is number {
    return typeof value === 'number';
  }

  getStatusSolutions(status: srk.RankProblemStatus) {
    return [...(status.solutions || [])].reverse();
  }

  statusCellClass(status: srk.RankProblemStatus) {
    const classNames = ['srk-prest-status-block', 'srk--text-center', 'srk--nowrap'];
    if (this.isStatusClickable(status)) {
      classNames.push('srk--cursor-pointer');
    }
    if (this.statusColorAsText) {
      classNames.push('srk-prest-status-block-color-text');
    }
    if (status.result === 'FB') {
      classNames.push('srk-prest-status-block-fb');
    } else if (status.result === 'AC') {
      classNames.push('srk-prest-status-block-accepted');
    } else if (status.result === '?') {
      classNames.push('srk-prest-status-block-frozen');
    } else if (status.result === 'RJ') {
      classNames.push('srk-prest-status-block-failed');
    }
    return classNames.join(' ');
  }

  isStatusClickable(status: srk.RankProblemStatus) {
    return this.getStatusSolutions(status).length > 0;
  }

  statusCellRole(status: srk.RankProblemStatus) {
    return this.isStatusClickable(status) ? 'button' : null;
  }

  statusCellTabIndex(status: srk.RankProblemStatus) {
    return this.isStatusClickable(status) ? 0 : null;
  }

  buildUserCellContext(row: StaticRanklistRow, rowIndex: number): UserCellTemplateContext {
    return {
      $implicit: row.user,
      user: row.user,
      row,
      rowIndex,
      ranklist: this.data,
      markers: this.data.markers,
      hideOrganization: this.splitOrganization,
      hideAvatar: this.showAvatarInOrganization(),
      onClick: (event?: MouseEvent) => this.emitUserClick(event, row, rowIndex),
    };
  }

  buildStatusCellContext(
    row: StaticRanklistRow,
    rowIndex: number,
    status: srk.RankProblemStatus,
    problemIndex: number,
  ): StatusCellTemplateContext {
    return {
      $implicit: status,
      status,
      problem: this.data.problems[problemIndex],
      problemIndex,
      user: row.user,
      row,
      rowIndex,
      ranklist: this.data,
      solutions: this.getStatusSolutions(status),
      statusCellPreset: this.statusCellPreset,
      statusColorAsText: this.statusColorAsText,
      emptyStatusPlaceholder: this.emptyStatusPlaceholder,
      onClick: (event?: MouseEvent) => this.emitSolutionClick(event, row, rowIndex, status, problemIndex),
    };
  }

  activateUserCellFromKeyboard(event: Event, row: StaticRanklistRow, rowIndex: number) {
    event.preventDefault();
    this.emitUserClick(undefined, row, rowIndex);
  }

  activateStatusCellFromKeyboard(
    event: Event,
    row: StaticRanklistRow,
    rowIndex: number,
    status: srk.RankProblemStatus,
    problemIndex: number,
  ) {
    event.preventDefault();
    this.emitSolutionClick(undefined, row, rowIndex, status, problemIndex);
  }

  emitUserClick(event: MouseEvent | undefined, row: StaticRanklistRow, rowIndex: number) {
    if (event) {
      captureModalTriggerPointFromMouseEvent(event, {
        source: 'user-cell',
        context: {
          rowIndex,
          userId: row.user.id || null,
          userName: this.resolveDisplayText(row.user.name),
        },
      });
    }
    this.userClick.emit({
      user: row.user,
      row,
      rowIndex,
      ranklist: this.data,
    });
  }

  emitSolutionClick(
    event: MouseEvent | undefined,
    row: StaticRanklistRow,
    rowIndex: number,
    status: srk.RankProblemStatus,
    problemIndex: number,
  ) {
    const solutions = this.getStatusSolutions(status);
    if (!solutions.length) {
      return;
    }
    if (event) {
      captureModalTriggerPointFromMouseEvent(event, {
        source: 'status-cell',
        context: {
          rowIndex,
          problemIndex,
          problemAlias: this.data.problems[problemIndex]?.alias || null,
          problemTitle: this.data.problems[problemIndex] ? this.resolveDisplayText(this.data.problems[problemIndex].title) : null,
          userId: row.user.id || null,
        },
      });
    }
    this.solutionClick.emit({
      user: row.user,
      row,
      rowIndex,
      problemIndex,
      problem: this.data.problems[problemIndex],
      status,
      solutions,
      ranklist: this.data,
    });
  }

  private resolveSeriesSegment(rankValue: RankValue, series: srk.RankSeries | undefined) {
    const index = rankValue.segmentIndex || rankValue.segmentIndex === 0 ? rankValue.segmentIndex : -1;
    return (series?.segments || [])[index] || {};
  }

  isSeriesSegmentedColumn(series: srk.RankSeries | undefined) {
    return (series?.segments || []).some((segment) => typeof segment.style === 'string');
  }

  getSeriesSegmentClass(rankValue: RankValue, series: srk.RankSeries | undefined) {
    const segmentStyle = this.resolveSeriesSegment(rankValue, series).style;
    return typeof segmentStyle === 'string' ? `srk-preset-series-segment-${segmentStyle}` : '';
  }

  getSeriesSegmentStyle(rankValue: RankValue, series: srk.RankSeries | undefined) {
    const emptyColor: ThemeColor = {
      [EnumTheme.light]: undefined,
      [EnumTheme.dark]: undefined,
    };
    const segmentStyle = this.resolveSeriesSegment(rankValue, series).style;
    if (!segmentStyle || typeof segmentStyle === 'string') {
      return {};
    }
    const style = resolveStyle(segmentStyle);
    const textColor = style.textColor || emptyColor;
    const backgroundColor = style.backgroundColor || emptyColor;
    return {
      color: textColor[this.theme],
      backgroundColor: backgroundColor[this.theme],
    };
  }

  getProblemStatisticsFooterCellPrimary(key: string, stat: ProblemStatisticsFooter) {
    switch (key) {
      case 'accepted':
        return stat.accepted;
      case 'tried':
        return stat.tried;
      case 'submitted':
        return stat.submitted;
      case 'dirt':
        return stat.dirt;
      case 'se':
        return formatProblemStatisticsAverageHardness(stat);
      case 'firstAccepted':
        return formatProblemStatisticsAcceptedMinute(stat.firstAcceptedTime);
      case 'lastAccepted':
        return formatProblemStatisticsAcceptedMinute(stat.lastAcceptedTime);
      default:
        return '';
    }
  }

  getProblemStatisticsFooterCellSecondary(key: string, stat: ProblemStatisticsFooter) {
    switch (key) {
      case 'accepted':
        return formatProblemStatisticsPercent(stat.accepted, stat.participantCount);
      case 'tried':
        return formatProblemStatisticsPercent(stat.tried, stat.participantCount);
      case 'dirt':
        return formatProblemStatisticsPercent(stat.dirt, stat.dirtSubmitted);
      default:
        return undefined;
    }
  }
}

// packages/svelte/src/Ranklist.svelte
<script>
  import {
    EnumTheme,
    formatTimeDuration,
    numberToAlphabet,
    resolveStyle,
    resolveText,
    resolveUserMarkers,
  } from '@algoux/standard-ranklist-utils';
  import { createEventDispatcher } from 'svelte';
  import {
    calculateDirtPercentage,
    calculateProblemStatisticsFooter,
    calculateSEValue,
    captureModalTriggerPointFromMouseEvent,
    formatProblemStatisticsAcceptedMinute,
    formatProblemStatisticsAverageHardness,
    formatProblemStatisticsPercent,
    getMarkerPresentation,
    getProblemHeaderBackgroundImage,
    getRankProblemStatusCellPresentation,
    resolveSrkAssetUrl,
    shouldShowTimeColumn,
  } from '@algoux/standard-ranklist-renderer-component-core';
  import { caniuse, srkSupportedVersions } from '@algoux/standard-ranklist-renderer-component-core';

  export let data;
  export let theme = EnumTheme.light;
  export let borderedRows = false;
  export let rowBordered = false;
  export let columnBordered = false;
  export let stripedRows = false;
  export let formatSrkAssetUrl = undefined;
  export let splitOrganization = false;
  export let columnTitles = undefined;
  export let statusCellPreset = 'classic';
  export let statusColorAsText = false;
  export let showProblemStatisticsFooter = false;
  export let showDirtColumn = false;
  export let showSEColumn = false;
  export let emptyStatusPlaceholder = null;
  export let userAvatarPlacement = 'user';

  const dispatch = createEventDispatcher();

  $: showTimeColumn = shouldShowTimeColumn(data.rows);
  $: isSupportedVersion = caniuse(data.version);
  $: showAvatarInOrganization = splitOrganization && userAvatarPlacement === 'organization';
  $: problemStatistics = showProblemStatisticsFooter || showSEColumn ? calculateProblemStatisticsFooter(data) : [];
  $: leftFooterColumnCount = data.series.length + 1 + 1 + (showTimeColumn ? 1 : 0) + (splitOrganization ? 1 : 0);

  const firstBloodStar = '\u2605';
  const footerRows = [
    {
      key: 'accepted',
      label: 'Accepted',
      tooltip: 'Number of participants who solved this problem',
    },
    {
      key: 'tried',
      label: 'Tried',
      tooltip: 'Number of participants who attempted this problem',
    },
    {
      key: 'submitted',
      label: 'Submitted',
      tooltip: 'Total number of valid submissions for this problem',
    },
    {
      key: 'dirt',
      label: 'Dirt',
      tooltip: 'Wrong submissions among participants who solved this problem',
    },
    {
      key: 'se',
      label: 'SE',
      tooltip: 'Average hardness, calculated as (participants - accepted) / participants',
    },
    {
      key: 'firstAccepted',
      label: 'FB at',
      tooltip: 'First Blood at, also known as first solve time, in minutes',
    },
    {
      key: 'lastAccepted',
      label: 'LB at',
      tooltip: 'Last Blood at, also known as last solve time, in minutes',
    },
  ];

  function formatAssetUrl(url, field) {
    return resolveSrkAssetUrl(url, field, formatSrkAssetUrl);
  }

  function getRankValues(row) {
    return row.rankValues || data.series.map(() => ({ rank: null, segmentIndex: null }));
  }

  function getRankText(rankValue, row) {
    return rankValue.rank ? rankValue.rank : row.user.official === false ? '＊' : '';
  }

  function resolveSeriesColumnTitle(series, index) {
    const seriesTitles = columnTitles && columnTitles.series;
    if (typeof seriesTitles === 'function') {
      return seriesTitles(series, index) ?? series.title;
    }
    if (Array.isArray(seriesTitles)) {
      return seriesTitles[index] ?? series.title;
    }
    return series.title;
  }

  function resolveColumnTitle(key, fallback) {
    return columnTitles && columnTitles[key] !== undefined ? columnTitles[key] : fallback;
  }

  function problemAlias(problem, problemIndex) {
    return problem.alias || numberToAlphabet(problemIndex);
  }

  function problemStatsTitle(statistics) {
    const ratio = statistics.submitted ? ((statistics.accepted / statistics.submitted) * 100).toFixed(1) : 0;
    return `${statistics.accepted} / ${statistics.submitted} (${ratio}%)`;
  }

  function getResolvedUserMarkers(user) {
    return resolveUserMarkers(user, data.markers || []).map((marker) => ({
      marker,
      presentation: getMarkerPresentation(marker, theme),
    }));
  }

  function markerClass(entry) {
    return `srk-marker srk-marker-dot srk--c-tooltip ${entry.presentation.className || ''}`;
  }

  function markerBackgroundColor(entry) {
    return entry.presentation.style && entry.presentation.style.backgroundColor;
  }

  function resolveSeriesSegment(rankValue, series) {
    const index = rankValue.segmentIndex || rankValue.segmentIndex === 0 ? rankValue.segmentIndex : -1;
    return ((series && series.segments) || [])[index] || {};
  }

  function getSeriesSegmentClass(rankValue, series) {
    const segmentStyle = resolveSeriesSegment(rankValue, series).style;
    return typeof segmentStyle === 'string' ? `srk-preset-series-segment-${segmentStyle}` : '';
  }

  function isSeriesSegmentedColumn(series) {
    return ((series && series.segments) || []).some((segment) => typeof segment.style === 'string');
  }

  function getSeriesSegmentStyle(rankValue, series) {
    const emptyColor = {
      [EnumTheme.light]: undefined,
      [EnumTheme.dark]: undefined,
    };
    const segmentStyle = resolveSeriesSegment(rankValue, series).style;
    if (!segmentStyle || typeof segmentStyle === 'string') {
      return {};
    }
    const style = resolveStyle(segmentStyle);
    const textColor = style.textColor || emptyColor;
    const backgroundColor = style.backgroundColor || emptyColor;
    return {
      color: textColor[theme],
      backgroundColor: backgroundColor[theme],
    };
  }

  function getStatusSolutions(status) {
    return [...(status.solutions || [])].reverse();
  }

  function hasSolutions(status) {
    return getStatusSolutions(status).length > 0;
  }

  function statusCellClass(status) {
    const classNames = ['srk-prest-status-block', 'srk--text-center', 'srk--nowrap'];
    if (hasSolutions(status)) {
      classNames.push('srk--cursor-pointer');
    }
    if (statusColorAsText) {
      classNames.push('srk-prest-status-block-color-text');
    }
    if (status.result === 'FB') {
      classNames.push('srk-prest-status-block-fb');
    } else if (status.result === 'AC') {
      classNames.push('srk-prest-status-block-accepted');
    } else if (status.result === '?') {
      classNames.push('srk-prest-status-block-frozen');
    } else if (status.result === 'RJ') {
      classNames.push('srk-prest-status-block-failed');
    }
    return classNames.join(' ');
  }

  function statusPresentation(status) {
    return getRankProblemStatusCellPresentation(status, data, statusCellPreset);
  }

  function footerCellPrimary(key, stat) {
    switch (key) {
      case 'accepted':
        return stat.accepted;
      case 'tried':
        return stat.tried;
      case 'submitted':
        return stat.submitted;
      case 'dirt':
        return stat.dirt;
      case 'se':
        return formatProblemStatisticsAverageHardness(stat);
      case 'firstAccepted':
        return formatProblemStatisticsAcceptedMinute(stat.firstAcceptedTime);
      case 'lastAccepted':
        return formatProblemStatisticsAcceptedMinute(stat.lastAcceptedTime);
      default:
        return '';
    }
  }

  function footerCellSecondary(key, stat) {
    switch (key) {
      case 'accepted':
        return formatProblemStatisticsPercent(stat.accepted, stat.participantCount);
      case 'tried':
        return formatProblemStatisticsPercent(stat.tried, stat.participantCount);
      case 'dirt':
        return formatProblemStatisticsPercent(stat.dirt, stat.dirtSubmitted);
      default:
        return undefined;
    }
  }

  function emitUserClick(event, row, rowIndex) {
    if (event) {
      captureModalTriggerPointFromMouseEvent(event, {
        source: 'user-cell',
        context: {
          rowIndex,
          userId: row.user.id || null,
          userName: resolveText(row.user.name),
        },
      });
    }
    dispatch('userClick', {
      user: row.user,
      row,
      rowIndex,
      ranklist: data,
    });
  }

  function emitSolutionClick(event, row, rowIndex, status, problemIndex) {
    const solutions = getStatusSolutions(status);
    if (!solutions.length) {
      return;
    }
    if (event) {
      captureModalTriggerPointFromMouseEvent(event, {
        source: 'status-cell',
        context: {
          rowIndex,
          problemIndex,
          problemAlias: data.problems[problemIndex] && data.problems[problemIndex].alias,
          problemTitle: data.problems[problemIndex] ? resolveText(data.problems[problemIndex].title) : null,
          userId: row.user.id || null,
        },
      });
    }
    dispatch('solutionClick', {
      user: row.user,
      row,
      rowIndex,
      problemIndex,
      problem: data.problems[problemIndex],
      status,
      solutions,
      ranklist: data,
    });
  }
</script>

{#if data.type !== 'general'}
  <div>srk type "{data.type}" is not supported</div>
{:else if !isSupportedVersion}
  <div>srk version "{data.version}" is not supported (current supported: {srkSupportedVersions})</div>
{:else}
  <div class="srk-common-table srk-main">
    <table
      class:srk-table-row-bordered={borderedRows || rowBordered}
      class:srk-table-column-bordered={columnBordered}
      class:srk-table-row-striped={stripedRows}
    >
      <thead>
        <tr>
          {#each data.series as seriesItem, seriesIndex}
            <th
              class="srk-series-header srk--text-right srk--nowrap"
              class:srk-series-segmented-column={isSeriesSegmentedColumn(seriesItem)}
            >
              {resolveSeriesColumnTitle(seriesItem, seriesIndex)}
            </th>
          {/each}
          {#if splitOrganization}
            <th class="srk-organization-header srk--text-left srk--nowrap">
              {resolveColumnTitle('organization', 'Organization')}
            </th>
          {/if}
          <th class="srk--text-left srk--nowrap">{resolveColumnTitle('user', 'Name')}</th>
          <th class="srk--text-right srk--nowrap">{resolveColumnTitle('score', 'Score')}</th>
          {#if showTimeColumn}
            <th class="srk--text-right srk--nowrap">{resolveColumnTitle('time', 'Time')}</th>
          {/if}
          {#each data.problems as problem, problemIndex}
            <th
              class="srk--nowrap srk-problem-header"
              style:background-image={getProblemHeaderBackgroundImage(problem.style, theme)}
            >
              <slot name="problem-header-cell" {problem} {problemIndex} index={problemIndex} {theme}>
                {#if problem.link}
                  <a href={problem.link} target="_blank" rel="noopener noreferrer" style="color: unset">
                    <span class="srk--display-block">{problemAlias(problem, problemIndex)}</span>
                    {#if problem.statistics}
                      <span class="srk--display-block srk-problem-stats" title={problemStatsTitle(problem.statistics)}>
                        {problem.statistics.accepted}
                      </span>
                    {/if}
                  </a>
                {:else}
                  <span class="srk--display-block">{problemAlias(problem, problemIndex)}</span>
                  {#if problem.statistics}
                    <span class="srk--display-block srk-problem-stats" title={problemStatsTitle(problem.statistics)}>
                      {problem.statistics.accepted}
                    </span>
                  {/if}
                {/if}
              </slot>
            </th>
          {/each}
          {#if showDirtColumn}
            <th class="srk-dirt-header srk--text-right srk--nowrap">{resolveColumnTitle('dirt', 'Dirt')}</th>
          {/if}
          {#if showSEColumn}
            <th class="srk-se-header srk--text-right srk--nowrap">{resolveColumnTitle('se', 'SE')}</th>
          {/if}
        </tr>
      </thead>
      <tbody>
        {#each data.rows as row, rowIndex}
          <tr>
            {#each getRankValues(row) as rankValue, seriesIndex}
              <td
                class={`srk--text-right srk--nowrap ${getSeriesSegmentClass(rankValue, data.series[seriesIndex])}`}
                class:srk-series-segmented-column={isSeriesSegmentedColumn(data.series[seriesIndex])}
                style:color={getSeriesSegmentStyle(rankValue, data.series[seriesIndex]).color}
                style:background-color={getSeriesSegmentStyle(rankValue, data.series[seriesIndex]).backgroundColor}
              >
                {getRankText(rankValue, row)}
              </td>
            {/each}
            {#if splitOrganization}
              <td
                class="srk-organization-cell srk--text-left srk--nowrap"
                class:srk-organization-cell-avatar={showAvatarInOrganization && !!row.user.avatar}
              >
                <div class="srk-organization-cell-content">
                  {#if showAvatarInOrganization && row.user.avatar}
                    <div class="srk-user-avatar">
                      <img src={formatAssetUrl(row.user.avatar, 'user.avatar')} alt="User Avatar" />
                    </div>
                  {/if}
                  <span
                    class="srk-organization-name-text"
                    title={row.user.organization ? resolveText(row.user.organization) : ''}
                  >
                    {row.user.organization ? resolveText(row.user.organization) : ''}
                  </span>
                </div>
              </td>
            {/if}
            <slot
              name="user-cell"
              user={row.user}
              {row}
              {rowIndex}
              ranklist={data}
              markers={data.markers}
              {theme}
              hideOrganization={splitOrganization}
              hideAvatar={showAvatarInOrganization}
              onClick={(event) => emitUserClick(event, row, rowIndex)}
            >
              <!-- svelte-ignore a11y-click-events-have-key-events -->
              <td
                class="srk--text-left srk--nowrap srk-user-cell srk--cursor-pointer"
                title=""
                on:click|preventDefault={(event) => emitUserClick(event, row, rowIndex)}
              >
                <div class="srk-user-cell-content">
                  {#if row.user.avatar && !showAvatarInOrganization}
                    <div class="srk-user-avatar">
                      <img src={formatAssetUrl(row.user.avatar, 'user.avatar')} alt="User Avatar" />
                    </div>
                  {/if}
                  <div class="srk-user-body">
                    <div class="srk-user-name-row">
                      <span class="srk-user-name-text" title={resolveText(row.user.name)}>
                        {resolveText(row.user.name)}
                      </span>
                      <span class="srk-marker-dot-group">
                        {#each getResolvedUserMarkers(row.user) as entry}
                          <span
                            class={markerClass(entry)}
                            style:background-color={markerBackgroundColor(entry)}
                            data-tooltip={resolveText(entry.marker.label)}
                          ></span>
                        {/each}
                      </span>
                    </div>
                    {#if row.user.organization && !splitOrganization}
                      <p class="srk-user-secondary-text srk--text-ellipsis" title="">
                        {resolveText(row.user.organization)}
                      </p>
                    {/if}
                  </div>
                </div>
              </td>
            </slot>
            <td class="srk--text-right srk--nowrap">{row.score.value}</td>
            {#if showTimeColumn}
              <td class="srk--text-right srk--nowrap">
                {row.score.time ? formatTimeDuration(row.score.time, 'min', Math.floor) : '-'}
              </td>
            {/if}
            {#each row.statuses as status, problemIndex}
              <slot
                name="status-cell"
                {status}
                problem={data.problems[problemIndex]}
                {problemIndex}
                user={row.user}
                {row}
                {rowIndex}
                ranklist={data}
                solutions={getStatusSolutions(status)}
                statusCellPreset={statusCellPreset}
                statusColorAsText={statusColorAsText}
                emptyStatusPlaceholder={emptyStatusPlaceholder}
                onClick={(event) => emitSolutionClick(event, row, rowIndex, status, problemIndex)}
              >
                {#if status.result === 'FB' || status.result === 'AC'}
                  {@const presentation = statusPresentation(status)}
                  <!-- svelte-ignore a11y-click-events-have-key-events -->
                  <td
                    class={statusCellClass(status)}
                    on:click|preventDefault={(event) => emitSolutionClick(event, row, rowIndex, status, problemIndex)}
                  >
                    {#if statusColorAsText && status.result === 'FB'}
                      <span class="srk-prest-status-block-fb-star">{firstBloodStar}</span>
                    {/if}
                    {#if typeof presentation.score === 'number'}
                      <span class="srk-prest-status-block-score">{presentation.score}</span>
                      <span class="srk-prest-status-block-score-details">{presentation.scoreDetails}</span>
                    {:else if presentation.secondary !== undefined}
                      <span class="srk-prest-status-block-primary">{presentation.primary || ''}</span>{' '}<span class="srk-prest-status-block-secondary">{presentation.secondary}</span>
                    {:else}
                      {presentation.primary}
                    {/if}
                  </td>
                {:else if status.result === '?' || status.result === 'RJ'}
                  {@const presentation = statusPresentation(status)}
                  <!-- svelte-ignore a11y-click-events-have-key-events -->
                  <td
                    class={statusCellClass(status)}
                    on:click|preventDefault={(event) => emitSolutionClick(event, row, rowIndex, status, problemIndex)}
                  >
                    {#if presentation.secondary !== undefined}
                      <span class="srk-prest-status-block-primary">{presentation.primary || ''}</span>{' '}<span class="srk-prest-status-block-secondary">{presentation.secondary}</span>
                    {:else}
                      {presentation.primary}
                    {/if}
                  </td>
                {:else}
                  <td class="srk-status-placeholder-cell srk--text-center srk--nowrap">
                    {emptyStatusPlaceholder == null ? '' : emptyStatusPlaceholder}
                  </td>
                {/if}
              </slot>
            {/each}
            {#if showDirtColumn}
              <td class="srk-dirt-cell srk--text-right srk--nowrap">{calculateDirtPercentage(row)}</td>
            {/if}
            {#if showSEColumn}
              <td class="srk-se-cell srk--text-right srk--nowrap">{calculateSEValue(row, problemStatistics)}</td>
            {/if}
          </tr>
        {/each}
      </tbody>
      {#if showProblemStatisticsFooter}
        <tfoot>
          {#each footerRows as footerRow}
            <tr class="srk-problem-statistics-footer-row">
              <td class="srk-problem-statistics-footer-labels srk--text-right srk--nowrap" colspan={leftFooterColumnCount}>
                <span class="srk-problem-statistics-footer-label srk--c-tooltip" data-tooltip={footerRow.tooltip}>
                  {footerRow.label}
                </span>
              </td>
              {#each problemStatistics as stat}
                {@const secondary = footerCellSecondary(footerRow.key, stat)}
                <td class="srk-problem-statistics-footer-cell srk--text-center srk--nowrap">
                  <span class="srk-problem-statistics-footer-primary">{footerCellPrimary(footerRow.key, stat)}</span>
                  {#if secondary !== undefined}
                    {' '}<span class="srk-problem-statistics-footer-secondary">{secondary}</span>
                  {/if}
                </td>
              {/each}
              {#if showDirtColumn}
                <td class="srk-problem-statistics-footer-cell srk-extra-statistics-footer-cell srk-dirt-footer-cell srk--nowrap">
                  <span class="srk-problem-statistics-footer-primary"></span>
                </td>
              {/if}
              {#if showSEColumn}
                <td class="srk-problem-statistics-footer-cell srk-extra-statistics-footer-cell srk-se-footer-cell srk--nowrap">
                  <span class="srk-problem-statistics-footer-primary"></span>
                </td>
              {/if}
            </tr>
          {/each}
          <tr class="srk-problem-statistics-footer-row srk-problem-statistics-footer-problem-label-row">
            <td class="srk-problem-statistics-footer-labels srk--text-right srk--nowrap" colspan={leftFooterColumnCount}></td>
            {#each data.problems as problem, problemIndex}
              <td
                class="srk-problem-statistics-footer-cell srk-problem-statistics-footer-problem-header srk-problem-header srk--text-center srk--nowrap"
                style:background-image={getProblemHeaderBackgroundImage(problem.style, theme, 0)}
              >
                <span class="srk--display-block">{problem.alias || numberToAlphabet(problemIndex)}</span>
              </td>
            {/each}
            {#if showDirtColumn}
              <td class="srk-problem-statistics-footer-cell srk-extra-statistics-footer-cell srk-dirt-footer-cell srk--nowrap">
                <span class="srk-problem-statistics-footer-primary"></span>
              </td>
            {/if}
            {#if showSEColumn}
              <td class="srk-problem-statistics-footer-cell srk-extra-statistics-footer-cell srk-se-footer-cell srk--nowrap">
                <span class="srk-problem-statistics-footer-primary"></span>
              </td>
            {/if}
          </tr>
        </tfoot>
      {/if}
    </table>
  </div>
{/if}
