// packages/react/dev/App.tsx
import React from 'react';
import type * as srk from '@algoux/standard-ranklist';
import type {
  ProblemClickPayload,
  RanklistColumnTitles,
  RanklistStatusCellPreset,
  RanklistUserAvatarPlacement,
  SolutionClickPayload,
  StaticRanklist,
  UserClickPayload,
} from '../src';
import data from '../../../demo.json';
import {
  DefaultSolutionModal,
  DefaultUserModal,
  Modal,
  Ranklist,
  convertToStaticRanklist,
} from '../src';
import * as Utils from '@algoux/standard-ranklist-utils';
import { ProgressBar } from '../src';

function resolvePreferredTheme() {
  if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') {
    return Utils.EnumTheme.light;
  }

  try {
    return window.matchMedia('(prefers-color-scheme: dark)').matches
      ? Utils.EnumTheme.dark
      : Utils.EnumTheme.light;
  } catch {
    return Utils.EnumTheme.light;
  }
}

interface AppState {
  data: srk.Ranklist;
  solutions: srk.Solution[];
  activeUserClick: UserClickPayload | null;
  activeProblemClick: ProblemClickPayload | null;
  activeSolutionClick: SolutionClickPayload | null;
  splitOrganization: boolean;
  useCustomColumnTitles: boolean;
  statusCellPreset: RanklistStatusCellPreset;
  statusColorAsText: boolean;
  showProblemStatisticsFooter: boolean;
  showDirtColumn: boolean;
  showSEColumn: boolean;
  rowBordered: boolean;
  columnBordered: boolean;
  emptyStatusPlaceholder: string | null;
  userAvatarPlacement: RanklistUserAvatarPlacement;
  language: LanguageOptionValue;
}

const demoColumnTitles: RanklistColumnTitles = {
  series: (series, index) => (index === 0 ? 'Rank' : series.title || `Series ${index + 1}`),
  organization: 'School',
  user: 'Team',
  score: 'Solved',
  time: 'Penalty',
  dirt: 'Dirt',
  se: 'SE',
};

const statusPresetOptions: Array<{ value: RanklistStatusCellPreset; label: string }> = [
  { value: 'classic', label: 'Classic' },
  { value: 'detailed', label: 'Detailed' },
  { value: 'minimal', label: 'Minimal' },
  { value: 'compact', label: 'Compact' },
];

const emptyStatusPlaceholderOptions = [
  { value: '', label: 'None' },
  { value: '·', label: 'Dot' },
  { value: '-', label: 'Dash' },
];

const userAvatarPlacementOptions: Array<{ value: RanklistUserAvatarPlacement; label: string }> = [
  { value: 'user', label: 'User' },
  { value: 'organization', label: 'Organization' },
];

type LanguageOptionValue = 'browser' | 'zh-CN' | 'en-US';

const languageOptions: Array<{ value: LanguageOptionValue; label: string }> = [
  { value: 'browser', label: 'Browser' },
  { value: 'zh-CN', label: 'zh-CN' },
  { value: 'en-US', label: 'en-US' },
];

export default class App extends React.Component<Record<string, never>, AppState> {
  private readonly preferredTheme = resolvePreferredTheme();

  constructor(props: any) {
    super(props);
    this.state = {
      data: data as srk.Ranklist,
      solutions: Utils.getSortedCalculatedRawSolutions((data as srk.Ranklist).rows),
      activeUserClick: null,
      activeProblemClick: null,
      activeSolutionClick: null,
      splitOrganization: true,
      useCustomColumnTitles: true,
      statusCellPreset: 'compact',
      statusColorAsText: true,
      showProblemStatisticsFooter: true,
      showDirtColumn: true,
      showSEColumn: true,
      rowBordered: true,
      columnBordered: true,
      emptyStatusPlaceholder: '·',
      userAvatarPlacement: 'organization',
      language: 'browser',
    };
  }

  getStaticRanklist = (): StaticRanklist => convertToStaticRanklist(this.state.data) as StaticRanklist;

  getSelectedLanguages = (): readonly string[] | undefined => {
    return this.state.language === 'browser' ? undefined : [this.state.language];
  };

  handleTimeTravel = (time: number | null) => {
    if (time === null) {
      this.setState({
        data: data as srk.Ranklist,
        activeUserClick: null,
        activeProblemClick: null,
        activeSolutionClick: null,
      });
      return;
    }
    const filteredSolutions = Utils.filterSolutionsUntil(this.state.solutions, [time, 'ms']);
    const newSrk = Utils.regenerateRanklistBySolutions(data, filteredSolutions);
    this.setState({
      data: newSrk as srk.Ranklist,
      activeUserClick: null,
      activeProblemClick: null,
      activeSolutionClick: null,
    });
  };

  handleUserClick = (payload: UserClickPayload) => {
    this.setState({
      activeUserClick: payload,
      activeProblemClick: null,
      activeSolutionClick: null,
    });
  };

  handleProblemClick = (payload: ProblemClickPayload) => {
    this.setState({
      activeUserClick: null,
      activeProblemClick: payload,
      activeSolutionClick: null,
    });
  };

  handleSolutionClick = (payload: SolutionClickPayload) => {
    this.setState({
      activeUserClick: null,
      activeProblemClick: null,
      activeSolutionClick: payload,
    });
  };

  closeUserModal = () => {
    this.setState({ activeUserClick: null });
  };

  closeProblemModal = () => {
    this.setState({ activeProblemClick: null });
  };

  closeSolutionModal = () => {
    this.setState({ activeSolutionClick: null });
  };

  setBooleanOption = (key: BooleanRanklistOptionKey) => {
    this.setState((state) => ({
      [key]: !state[key],
    } as Pick<AppState, BooleanRanklistOptionKey>));
  };

  handleStatusPresetChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    this.setState({
      statusCellPreset: event.target.value as RanklistStatusCellPreset,
    });
  };

  handleEmptyStatusPlaceholderChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    this.setState({
      emptyStatusPlaceholder: event.target.value || null,
    });
  };

  handleUserAvatarPlacementChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    this.setState({
      userAvatarPlacement: event.target.value as RanklistUserAvatarPlacement,
    });
  };

  handleLanguageChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    this.setState({
      language: event.target.value as LanguageOptionValue,
    });
  };

  useBaselineOptions = () => {
    this.setState({
      splitOrganization: false,
      useCustomColumnTitles: false,
      statusCellPreset: 'classic',
      statusColorAsText: false,
      showProblemStatisticsFooter: false,
      showDirtColumn: false,
      showSEColumn: false,
      rowBordered: false,
      columnBordered: false,
      emptyStatusPlaceholder: null,
      userAvatarPlacement: 'user',
    });
  };

  useShowcaseOptions = () => {
    this.setState({
      splitOrganization: true,
      useCustomColumnTitles: true,
      statusCellPreset: 'compact',
      statusColorAsText: true,
      showProblemStatisticsFooter: true,
      showDirtColumn: true,
      showSEColumn: true,
      rowBordered: true,
      columnBordered: true,
      emptyStatusPlaceholder: '·',
      userAvatarPlacement: 'organization',
    });
  };

  render() {
    const staticRanklist = this.getStaticRanklist();
    const languages = this.getSelectedLanguages();
    const activeProblemClick = this.state.activeProblemClick;
    const activeProblem = activeProblemClick?.problem;
    const activeProblemTitle = activeProblem ? Utils.resolveText(activeProblem.title, languages) : '';
    const activeProblemIndex = activeProblemClick?.problemIndex ?? 0;

    return (
      <main className="preview-shell">
        <ProgressBar
          data={this.state.data}
          td={this.state.data._now ? Date.now() - new Date(this.state.data._now).getTime() : 0}
          live
          enableTimeTravel
          onTimeTravel={this.handleTimeTravel}
        />
        <div className="preview-spacer" />
        <section className="preview-controls" aria-label="Ranklist render options">
          <div className="preview-control-row preview-control-row-primary">
            <label className="preview-field preview-select-field">
              <span>Status preset</span>
              <select
                aria-label="Status preset"
                value={this.state.statusCellPreset}
                onChange={this.handleStatusPresetChange}
              >
                {statusPresetOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </label>
            <label className="preview-field preview-select-field">
              <span>Empty status placeholder</span>
              <select
                aria-label="Empty status placeholder"
                value={this.state.emptyStatusPlaceholder || ''}
                onChange={this.handleEmptyStatusPlaceholderChange}
              >
                {emptyStatusPlaceholderOptions.map((option) => (
                  <option key={option.value || 'none'} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </label>
            <label className="preview-field preview-select-field">
              <span>User avatar placement</span>
              <select
                aria-label="User avatar placement"
                value={this.state.userAvatarPlacement}
                onChange={this.handleUserAvatarPlacementChange}
              >
                {userAvatarPlacementOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </label>
            <label className="preview-field preview-select-field">
              <span>Language</span>
              <select
                aria-label="Language"
                value={this.state.language}
                onChange={this.handleLanguageChange}
              >
                {languageOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </label>
            <button type="button" className="preview-action" onClick={this.useShowcaseOptions}>
              Showcase
            </button>
            <button type="button" className="preview-action" onClick={this.useBaselineOptions}>
              Baseline
            </button>
          </div>
          <div className="preview-control-row">
            <ToggleField
              label="Split organization"
              checked={this.state.splitOrganization}
              onChange={() => this.setBooleanOption('splitOrganization')}
            />
            <ToggleField
              label="Custom column titles"
              checked={this.state.useCustomColumnTitles}
              onChange={() => this.setBooleanOption('useCustomColumnTitles')}
            />
            <ToggleField
              label="Text status colors"
              checked={this.state.statusColorAsText}
              onChange={() => this.setBooleanOption('statusColorAsText')}
            />
            <ToggleField
              label="Problem statistics footer"
              checked={this.state.showProblemStatisticsFooter}
              onChange={() => this.setBooleanOption('showProblemStatisticsFooter')}
            />
            <ToggleField
              label="Dirt column"
              checked={this.state.showDirtColumn}
              onChange={() => this.setBooleanOption('showDirtColumn')}
            />
            <ToggleField
              label="SE column"
              checked={this.state.showSEColumn}
              onChange={() => this.setBooleanOption('showSEColumn')}
            />
            <ToggleField
              label="Row borders"
              checked={this.state.rowBordered}
              onChange={() => this.setBooleanOption('rowBordered')}
            />
            <ToggleField
              label="Column borders"
              checked={this.state.columnBordered}
              onChange={() => this.setBooleanOption('columnBordered')}
            />
          </div>
        </section>
        <div className="preview-spacer" />
        <Ranklist
          data={staticRanklist}
          theme={this.preferredTheme}
          rowStriped
          onUserClick={this.handleUserClick}
          onProblemClick={this.handleProblemClick}
          onSolutionClick={this.handleSolutionClick}
          splitOrganization={this.state.splitOrganization}
          columnTitles={this.state.useCustomColumnTitles ? demoColumnTitles : undefined}
          statusCellPreset={this.state.statusCellPreset}
          statusColorAsText={this.state.statusColorAsText}
          showProblemStatisticsFooter={this.state.showProblemStatisticsFooter}
          showDirtColumn={this.state.showDirtColumn}
          showSEColumn={this.state.showSEColumn}
          rowBordered={this.state.rowBordered}
          columnBordered={this.state.columnBordered}
          emptyStatusPlaceholder={this.state.emptyStatusPlaceholder}
          userAvatarPlacement={this.state.userAvatarPlacement}
          languages={languages}
        />

        <DefaultUserModal
          open={!!this.state.activeUserClick}
          user={this.state.activeUserClick?.user}
          markers={staticRanklist.markers}
          theme={this.preferredTheme}
          languages={languages}
          onClose={this.closeUserModal}
        />

        <Modal
          open={!!activeProblemClick}
          onClose={this.closeProblemModal}
          rootClassName="srk-general-modal-root"
          title="Problem Info"
          width={420}
          wrapClassName="srk-problem-modal"
        >
          {activeProblem ? (
            <div>
              <p>Alias: {activeProblem.alias || activeProblemIndex + 1}</p>
              <p>Title: {activeProblemTitle || '-'}</p>
              <p>Index: {activeProblemIndex}</p>
              {activeProblem.link ? (
                <p>
                  Link:{' '}
                  <a href={activeProblem.link} target="_blank" rel="noopener noreferrer">
                    {activeProblem.link}
                  </a>
                </p>
              ) : null}
              {activeProblem.statistics ? (
                <p>
                  Stats: {activeProblem.statistics.accepted} accepted / {activeProblem.statistics.submitted}{' '}
                  submitted
                </p>
              ) : null}
            </div>
          ) : null}
        </Modal>

        <DefaultSolutionModal
          open={!!this.state.activeSolutionClick}
          user={this.state.activeSolutionClick?.user}
          problem={this.state.activeSolutionClick?.problem}
          problemIndex={this.state.activeSolutionClick?.problemIndex || 0}
          solutions={this.state.activeSolutionClick?.solutions || []}
          languages={languages}
          onClose={this.closeSolutionModal}
        />

        {/*
          Uncomment this block to keep the library's default user content, but try custom modal props.

          <DefaultUserModal
            open={!!this.state.activeUserClick}
            user={this.state.activeUserClick?.user}
            markers={staticRanklist.markers}
            theme={this.preferredTheme}
            title="Custom User Title"
            width={520}
            onClose={this.closeUserModal}
          />
        */}

        {/*
          Uncomment this block to replace DefaultUserModal with your own modal content.

          <Modal
            open={!!this.state.activeUserClick}
            onClose={this.closeUserModal}
            title={
              this.state.activeUserClick
                ? `Custom user: ${Utils.resolveText(this.state.activeUserClick.user.name)}`
                : 'Custom user'
            }
            width={520}
          >
            <pre style={{ whiteSpace: 'pre-wrap', margin: 0 }}>
              {JSON.stringify(this.state.activeUserClick, null, 2)}
            </pre>
          </Modal>
        */}

        {/*
          Uncomment this block to replace DefaultSolutionModal with your own modal content.

          <Modal
            open={!!this.state.activeSolutionClick}
            onClose={this.closeSolutionModal}
            title={
              this.state.activeSolutionClick
                ? `Custom solutions: ${this.state.activeSolutionClick.problem?.alias || this.state.activeSolutionClick.problemIndex + 1}`
                : 'Custom solutions'
            }
            width={520}
          >
            <pre style={{ whiteSpace: 'pre-wrap', margin: 0 }}>
              {JSON.stringify(this.state.activeSolutionClick, null, 2)}
            </pre>
          </Modal>
        */}
      </main>
    );
  }
}

type BooleanRanklistOptionKey =
  | 'splitOrganization'
  | 'useCustomColumnTitles'
  | 'statusColorAsText'
  | 'showProblemStatisticsFooter'
  | 'showDirtColumn'
  | 'showSEColumn'
  | 'rowBordered'
  | 'columnBordered';

function ToggleField({
  label,
  checked,
  onChange,
}: {
  label: string;
  checked: boolean;
  onChange: () => void;
}) {
  return (
    <label className="preview-field preview-toggle-field">
      <input type="checkbox" checked={checked} onChange={onChange} />
      <span>{label}</span>
    </label>
  );
}

// packages/vue/dev/App.vue
<template>
  <main class="preview-shell">
    <ProgressBar :data="ranklist" enable-time-travel live @time-travel="handleTimeTravel" />
    <div class="preview-spacer"></div>
    <section class="preview-controls" aria-label="Ranklist render options">
      <div class="preview-control-row preview-control-row-primary">
        <label class="preview-field preview-select-field">
          <span>Status preset</span>
          <select v-model="statusCellPreset" aria-label="Status preset">
            <option v-for="option in statusPresetOptions" :key="option.value" :value="option.value">
              {{ option.label }}
            </option>
          </select>
        </label>
        <label class="preview-field preview-select-field">
          <span>Empty status placeholder</span>
          <select v-model="emptyStatusPlaceholderValue" aria-label="Empty status placeholder">
            <option v-for="option in emptyStatusPlaceholderOptions" :key="option.value || 'none'" :value="option.value">
              {{ option.label }}
            </option>
          </select>
        </label>
        <label class="preview-field preview-select-field">
          <span>User avatar placement</span>
          <select v-model="userAvatarPlacement" aria-label="User avatar placement">
            <option v-for="option in userAvatarPlacementOptions" :key="option.value" :value="option.value">
              {{ option.label }}
            </option>
          </select>
        </label>
        <label class="preview-field preview-select-field">
          <span>Language</span>
          <select v-model="language" aria-label="Language">
            <option v-for="option in languageOptions" :key="option.value" :value="option.value">
              {{ option.label }}
            </option>
          </select>
        </label>
        <button type="button" class="preview-action" @click="useShowcaseOptions">Showcase</button>
        <button type="button" class="preview-action" @click="useBaselineOptions">Baseline</button>
      </div>
      <div class="preview-control-row">
        <label class="preview-field preview-toggle-field">
          <input v-model="splitOrganization" type="checkbox" aria-label="Split organization" />
          <span>Split organization</span>
        </label>
        <label class="preview-field preview-toggle-field">
          <input v-model="useCustomColumnTitles" type="checkbox" aria-label="Custom column titles" />
          <span>Custom column titles</span>
        </label>
        <label class="preview-field preview-toggle-field">
          <input v-model="statusColorAsText" type="checkbox" aria-label="Text status colors" />
          <span>Text status colors</span>
        </label>
        <label class="preview-field preview-toggle-field">
          <input v-model="showProblemStatisticsFooter" type="checkbox" aria-label="Problem statistics footer" />
          <span>Problem statistics footer</span>
        </label>
        <label class="preview-field preview-toggle-field">
          <input v-model="showDirtColumn" type="checkbox" aria-label="Dirt column" />
          <span>Dirt column</span>
        </label>
        <label class="preview-field preview-toggle-field">
          <input v-model="showSEColumn" type="checkbox" aria-label="SE column" />
          <span>SE column</span>
        </label>
        <label class="preview-field preview-toggle-field">
          <input v-model="rowBordered" type="checkbox" aria-label="Row borders" />
          <span>Row borders</span>
        </label>
        <label class="preview-field preview-toggle-field">
          <input v-model="columnBordered" type="checkbox" aria-label="Column borders" />
          <span>Column borders</span>
        </label>
      </div>
    </section>
    <div class="preview-spacer"></div>
    <Ranklist
      :data="staticRanklist"
      :theme="preferredTheme"
      row-striped
      :split-organization="splitOrganization"
      :column-titles="useCustomColumnTitles ? demoColumnTitles : undefined"
      :status-cell-preset="statusCellPreset"
      :status-color-as-text="statusColorAsText"
      :show-problem-statistics-footer="showProblemStatisticsFooter"
      :show-dirt-column="showDirtColumn"
      :show-s-e-column="showSEColumn"
      :row-bordered="rowBordered"
      :column-bordered="columnBordered"
      :empty-status-placeholder="emptyStatusPlaceholder"
      :user-avatar-placement="userAvatarPlacement"
      :languages="languages"
      @problem-click="handleProblemClick"
      @solution-click="handleSolutionClick"
      @user-click="handleUserClick"
    />
    <DefaultUserModal
      :open="!!activeUserClick"
      :user="activeUserClick?.user"
      :markers="staticRanklist.markers"
      :theme="preferredTheme"
      :languages="languages"
      @close="closeUserModal"
    />
    <DefaultSolutionModal
      :open="!!activeSolutionClick"
      :user="activeSolutionClick?.user"
      :problem="activeSolutionClick?.problem"
      :problem-index="activeSolutionClick?.problemIndex ?? 0"
      :solutions="activeSolutionClick?.solutions || []"
      :languages="languages"
      @close="closeSolutionModal"
    />
    <Modal
      :open="!!activeProblemClick"
      root-class-name="srk-general-modal-root"
      title="Problem Info"
      :width="420"
      wrap-class-name="srk-problem-modal"
      @close="closeProblemModal"
    >
      <div v-if="activeProblem">
        <p>Alias: {{ activeProblem.alias || activeProblemIndex + 1 }}</p>
        <p>Title: {{ activeProblemTitle || '-' }}</p>
        <p>Index: {{ activeProblemIndex }}</p>
        <p v-if="activeProblem.link">
          Link:
          <a :href="activeProblem.link" target="_blank" rel="noopener noreferrer">{{ activeProblem.link }}</a>
        </p>
        <p v-if="activeProblem.statistics">
          Stats: {{ activeProblem.statistics.accepted }} accepted / {{ activeProblem.statistics.submitted }} submitted
        </p>
      </div>
    </Modal>
  </main>
</template>

<script setup lang="ts">
import type * as srk from '@algoux/standard-ranklist';
import {
  EnumTheme,
  convertToStaticRanklist,
  filterSolutionsUntil,
  getSortedCalculatedRawSolutions,
  regenerateRanklistBySolutions,
  resolveText,
} from '@algoux/standard-ranklist-utils';
import { computed, ref } from 'vue';
import demoData from '../../../demo.json';
import type {
  RanklistColumnTitles,
  RanklistStatusCellPreset,
  RanklistUserAvatarPlacement,
  ProblemClickPayload,
  SolutionClickPayload,
  UserClickPayload,
} from '../src';
import { DefaultSolutionModal, DefaultUserModal, Modal, ProgressBar, Ranklist } from '../src';

const originalRanklist = demoData as srk.Ranklist;
const sortedSolutions = getSortedCalculatedRawSolutions(originalRanklist.rows);
const ranklist = ref<srk.Ranklist>(originalRanklist);
const activeUserClick = ref<UserClickPayload | null>(null);
const activeProblemClick = ref<ProblemClickPayload | null>(null);
const activeSolutionClick = ref<SolutionClickPayload | null>(null);
const staticRanklist = computed(() => convertToStaticRanklist(ranklist.value));
const preferredTheme = resolvePreferredTheme();
const splitOrganization = ref(true);
const useCustomColumnTitles = ref(true);
const statusCellPreset = ref<RanklistStatusCellPreset>('compact');
const statusColorAsText = ref(true);
const showProblemStatisticsFooter = ref(true);
const showDirtColumn = ref(true);
const showSEColumn = ref(true);
const rowBordered = ref(true);
const columnBordered = ref(true);
const emptyStatusPlaceholder = ref<string | null>('·');
const userAvatarPlacement = ref<RanklistUserAvatarPlacement>('organization');
type LanguageOptionValue = 'browser' | 'zh-CN' | 'en-US';
const language = ref<LanguageOptionValue>('browser');
const emptyStatusPlaceholderValue = computed({
  get: () => emptyStatusPlaceholder.value || '',
  set: (value: string) => {
    emptyStatusPlaceholder.value = value || null;
  },
});
const languages = computed(() => (language.value === 'browser' ? undefined : [language.value]));
const activeProblem = computed(() => activeProblemClick.value?.problem || null);
const activeProblemIndex = computed(() => activeProblemClick.value?.problemIndex ?? 0);
const activeProblemTitle = computed(() => (activeProblem.value ? resolveText(activeProblem.value.title, languages.value) : ''));

const demoColumnTitles: RanklistColumnTitles = {
  series: (series, index) => (index === 0 ? 'Rank' : series.title || `Series ${index + 1}`),
  organization: 'School',
  user: 'Team',
  score: 'Solved',
  time: 'Penalty',
  dirt: 'Dirt',
  se: 'SE',
};

const statusPresetOptions: Array<{ value: RanklistStatusCellPreset; label: string }> = [
  { value: 'classic', label: 'Classic' },
  { value: 'detailed', label: 'Detailed' },
  { value: 'minimal', label: 'Minimal' },
  { value: 'compact', label: 'Compact' },
];

const emptyStatusPlaceholderOptions = [
  { value: '', label: 'None' },
  { value: '·', label: 'Dot' },
  { value: '-', label: 'Dash' },
];

const userAvatarPlacementOptions: Array<{ value: RanklistUserAvatarPlacement; label: string }> = [
  { value: 'user', label: 'User' },
  { value: 'organization', label: 'Organization' },
];

const languageOptions: Array<{ value: LanguageOptionValue; label: string }> = [
  { value: 'browser', label: 'Browser' },
  { value: 'zh-CN', label: 'zh-CN' },
  { value: 'en-US', label: 'en-US' },
];

function resolvePreferredTheme() {
  if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') {
    return EnumTheme.light;
  }

  try {
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? EnumTheme.dark : EnumTheme.light;
  } catch {
    return EnumTheme.light;
  }
}

function handleTimeTravel(time: number | null) {
  if (time === null) {
    ranklist.value = originalRanklist;
  } else {
    ranklist.value = regenerateRanklistBySolutions(
      originalRanklist,
      filterSolutionsUntil(sortedSolutions, [time, 'ms']),
    ) as srk.Ranklist;
  }
  activeUserClick.value = null;
  activeProblemClick.value = null;
  activeSolutionClick.value = null;
}

function handleUserClick(payload: UserClickPayload) {
  activeUserClick.value = payload;
  activeProblemClick.value = null;
  activeSolutionClick.value = null;
}

function handleProblemClick(payload: ProblemClickPayload) {
  activeUserClick.value = null;
  activeProblemClick.value = payload;
  activeSolutionClick.value = null;
}

function handleSolutionClick(payload: SolutionClickPayload) {
  activeUserClick.value = null;
  activeProblemClick.value = null;
  activeSolutionClick.value = payload;
}

function closeUserModal() {
  activeUserClick.value = null;
}

function closeProblemModal() {
  activeProblemClick.value = null;
}

function closeSolutionModal() {
  activeSolutionClick.value = null;
}

function useBaselineOptions() {
  splitOrganization.value = false;
  useCustomColumnTitles.value = false;
  statusCellPreset.value = 'classic';
  statusColorAsText.value = false;
  showProblemStatisticsFooter.value = false;
  showDirtColumn.value = false;
  showSEColumn.value = false;
  rowBordered.value = false;
  columnBordered.value = false;
  emptyStatusPlaceholder.value = null;
  userAvatarPlacement.value = 'user';
}

function useShowcaseOptions() {
  splitOrganization.value = true;
  useCustomColumnTitles.value = true;
  statusCellPreset.value = 'compact';
  statusColorAsText.value = true;
  showProblemStatisticsFooter.value = true;
  showDirtColumn.value = true;
  showSEColumn.value = true;
  rowBordered.value = true;
  columnBordered.value = true;
  emptyStatusPlaceholder.value = '·';
  userAvatarPlacement.value = 'organization';
}
</script>
