// packages/svelte/dev/App.svelte
<script>
  import {
    EnumTheme,
    convertToStaticRanklist,
    filterSolutionsUntil,
    getSortedCalculatedRawSolutions,
    regenerateRanklistBySolutions,
    resolveText,
  } from '@algoux/standard-ranklist-utils';
  import demoData from '../../../demo.json';
  import { DefaultSolutionModal, DefaultUserModal, Modal, ProgressBar, Ranklist } from '../src';

  const originalRanklist = demoData;
  const sortedSolutions = getSortedCalculatedRawSolutions(originalRanklist.rows);
  let ranklist = originalRanklist;
  let activeUserClick = null;
  let activeProblemClick = null;
  let activeSolutionClick = null;
  let splitOrganization = true;
  let useCustomColumnTitles = true;
  let statusCellPreset = 'compact';
  let statusColorAsText = true;
  let showProblemStatisticsFooter = true;
  let showDirtColumn = true;
  let showSEColumn = true;
  let rowBordered = true;
  let columnBordered = true;
  let emptyStatusPlaceholderValue = '·';
  let userAvatarPlacement = 'organization';
  let language = 'browser';
  const preferredTheme = resolvePreferredTheme();
  const demoColumnTitles = {
    series: (series, index) => (index === 0 ? 'Rank' : series.title || `Series ${index + 1}`),
    organization: 'School',
    user: 'Team',
    score: 'Solved',
    time: 'Penalty',
    dirt: 'Dirt',
    se: 'SE',
  };
  const statusPresetOptions = [
    { value: 'classic', label: 'Classic' },
    { value: 'detailed', label: 'Detailed' },
    { value: 'minimal', label: 'Minimal' },
    { value: 'compact', label: 'Compact' },
  ];
  const emptyStatusPlaceholderOptions = [
    { value: '', label: 'None' },
    { value: '·', label: 'Dot' },
    { value: '-', label: 'Dash' },
  ];
  const userAvatarPlacementOptions = [
    { value: 'user', label: 'User' },
    { value: 'organization', label: 'Organization' },
  ];
  const languageOptions = [
    { value: 'browser', label: 'Browser' },
    { value: 'zh-CN', label: 'zh-CN' },
    { value: 'en-US', label: 'en-US' },
  ];

  $: emptyStatusPlaceholder = emptyStatusPlaceholderValue || null;
  $: languages = language === 'browser' ? undefined : [language];
  $: staticRanklist = (languages, convertToStaticRanklist(ranklist));
  $: activeProblem = activeProblemClick && activeProblemClick.problem;
  $: activeProblemIndex = activeProblemClick ? activeProblemClick.problemIndex : 0;
  $: activeProblemTitle = activeProblem ? resolveText(activeProblem.title, languages) : '';

  function resolvePreferredTheme() {
    if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') {
      return EnumTheme.light;
    }

    try {
      return window.matchMedia('(prefers-color-scheme: dark)').matches ? EnumTheme.dark : EnumTheme.light;
    } catch {
      return EnumTheme.light;
    }
  }

  function handleTimeTravel(event) {
    const time = event.detail;
    if (time === null) {
      ranklist = originalRanklist;
    } else {
      ranklist = regenerateRanklistBySolutions(
        originalRanklist,
        filterSolutionsUntil(sortedSolutions, [time, 'ms']),
      );
    }
    activeUserClick = null;
    activeProblemClick = null;
    activeSolutionClick = null;
  }

  function handleUserClick(event) {
    activeUserClick = event.detail;
    activeProblemClick = null;
    activeSolutionClick = null;
  }

  function handleProblemClick(payload) {
    activeUserClick = null;
    activeProblemClick = payload;
    activeSolutionClick = null;
  }

  function handleSolutionClick(event) {
    activeUserClick = null;
    activeProblemClick = null;
    activeSolutionClick = event.detail;
  }

  function useBaselineOptions() {
    splitOrganization = false;
    useCustomColumnTitles = false;
    statusCellPreset = 'classic';
    statusColorAsText = false;
    showProblemStatisticsFooter = false;
    showDirtColumn = false;
    showSEColumn = false;
    rowBordered = false;
    columnBordered = false;
    emptyStatusPlaceholderValue = '';
    userAvatarPlacement = 'user';
  }

  function useShowcaseOptions() {
    splitOrganization = true;
    useCustomColumnTitles = true;
    statusCellPreset = 'compact';
    statusColorAsText = true;
    showProblemStatisticsFooter = true;
    showDirtColumn = true;
    showSEColumn = true;
    rowBordered = true;
    columnBordered = true;
    emptyStatusPlaceholderValue = '·';
    userAvatarPlacement = 'organization';
  }
</script>

<main class="preview-shell">
  <ProgressBar
    data={ranklist}
    td={ranklist._now ? Date.now() - new Date(ranklist._now).getTime() : 0}
    live
    enableTimeTravel
    on:timeTravel={handleTimeTravel}
  />
  <div class="preview-spacer"></div>
  <section class="preview-controls" aria-label="Ranklist render options">
    <div class="preview-control-row preview-control-row-primary">
      <label class="preview-field preview-select-field">
        <span>Status preset</span>
        <select aria-label="Status preset" bind:value={statusCellPreset}>
          {#each statusPresetOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
      </label>
      <label class="preview-field preview-select-field">
        <span>Empty status placeholder</span>
        <select aria-label="Empty status placeholder" bind:value={emptyStatusPlaceholderValue}>
          {#each emptyStatusPlaceholderOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
      </label>
      <label class="preview-field preview-select-field">
        <span>User avatar placement</span>
        <select aria-label="User avatar placement" bind:value={userAvatarPlacement}>
          {#each userAvatarPlacementOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
      </label>
      <label class="preview-field preview-select-field">
        <span>Language</span>
        <select aria-label="Language" bind:value={language}>
          {#each languageOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
      </label>
      <button type="button" class="preview-action" on:click={useShowcaseOptions}>Showcase</button>
      <button type="button" class="preview-action" on:click={useBaselineOptions}>Baseline</button>
    </div>
    <div class="preview-control-row">
      <label class="preview-field preview-toggle-field">
        <input type="checkbox" aria-label="Split organization" bind:checked={splitOrganization} />
        <span>Split organization</span>
      </label>
      <label class="preview-field preview-toggle-field">
        <input type="checkbox" aria-label="Custom column titles" bind:checked={useCustomColumnTitles} />
        <span>Custom column titles</span>
      </label>
      <label class="preview-field preview-toggle-field">
        <input type="checkbox" aria-label="Text status colors" bind:checked={statusColorAsText} />
        <span>Text status colors</span>
      </label>
      <label class="preview-field preview-toggle-field">
        <input type="checkbox" aria-label="Problem statistics footer" bind:checked={showProblemStatisticsFooter} />
        <span>Problem statistics footer</span>
      </label>
      <label class="preview-field preview-toggle-field">
        <input type="checkbox" aria-label="Dirt column" bind:checked={showDirtColumn} />
        <span>Dirt column</span>
      </label>
      <label class="preview-field preview-toggle-field">
        <input type="checkbox" aria-label="SE column" bind:checked={showSEColumn} />
        <span>SE column</span>
      </label>
      <label class="preview-field preview-toggle-field">
        <input type="checkbox" aria-label="Row borders" bind:checked={rowBordered} />
        <span>Row borders</span>
      </label>
      <label class="preview-field preview-toggle-field">
        <input type="checkbox" aria-label="Column borders" bind:checked={columnBordered} />
        <span>Column borders</span>
      </label>
    </div>
  </section>
  <div class="preview-spacer"></div>
  <Ranklist
    data={staticRanklist}
    theme={preferredTheme}
    rowStriped
    {splitOrganization}
    columnTitles={useCustomColumnTitles ? demoColumnTitles : undefined}
    {statusCellPreset}
    {statusColorAsText}
    {showProblemStatisticsFooter}
    {showDirtColumn}
    {showSEColumn}
    {rowBordered}
    {columnBordered}
    {emptyStatusPlaceholder}
    {userAvatarPlacement}
    {languages}
    onProblemClick={handleProblemClick}
    on:solutionClick={handleSolutionClick}
    on:userClick={handleUserClick}
  />
  <DefaultUserModal
    open={!!activeUserClick}
    user={activeUserClick && activeUserClick.user}
    markers={staticRanklist.markers}
    theme={preferredTheme}
    {languages}
    on:close={() => (activeUserClick = null)}
  />
  <Modal
    open={!!activeProblemClick}
    rootClassName="srk-general-modal-root"
    title="Problem Info"
    width={420}
    wrapClassName="srk-problem-modal"
    on:close={() => (activeProblemClick = null)}
  >
    {#if activeProblem}
      <div>
        <p>Alias: {activeProblem.alias || activeProblemIndex + 1}</p>
        <p>Title: {activeProblemTitle || '-'}</p>
        <p>Index: {activeProblemIndex}</p>
        {#if activeProblem.link}
          <p>Link: <a href={activeProblem.link} target="_blank" rel="noopener noreferrer">{activeProblem.link}</a></p>
        {/if}
        {#if activeProblem.statistics}
          <p>
            Stats: {activeProblem.statistics.accepted} accepted / {activeProblem.statistics.submitted} submitted
          </p>
        {/if}
      </div>
    {/if}
  </Modal>
  <DefaultSolutionModal
    open={!!activeSolutionClick}
    user={activeSolutionClick && activeSolutionClick.user}
    problem={activeSolutionClick && activeSolutionClick.problem}
    problemIndex={(activeSolutionClick && activeSolutionClick.problemIndex) || 0}
    solutions={(activeSolutionClick && activeSolutionClick.solutions) || []}
    {languages}
    on:close={() => (activeSolutionClick = null)}
  />
</main>

// packages/angular/dev/app.component.ts
import type * as srk from '@algoux/standard-ranklist';
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import {
  EnumTheme,
  convertToStaticRanklist,
  filterSolutionsUntil,
  getSortedCalculatedRawSolutions,
  regenerateRanklistBySolutions,
  resolveText,
} from '@algoux/standard-ranklist-utils';
import demoData from '../../../demo.json';
import {
  DefaultSolutionModalComponent,
  DefaultUserModalComponent,
  ModalComponent,
  ProgressBarComponent,
  RanklistComponent,
  type ProblemClickPayload,
  type RanklistColumnTitles,
  type RanklistStatusCellPreset,
  type RanklistUserAvatarPlacement,
  type SolutionClickPayload,
  type StaticRanklist,
  type UserClickPayload,
} from '../src/lib/index';

function resolvePreferredTheme() {
  if (typeof window === 'undefined' || typeof window.matchMedia !== 'function') {
    return EnumTheme.light;
  }

  try {
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? EnumTheme.dark : EnumTheme.light;
  } catch {
    return EnumTheme.light;
  }
}

type LanguageOptionValue = 'browser' | 'zh-CN' | 'en-US';

@Component({
  selector: 'srk-angular-preview',
  standalone: true,
  imports: [
    CommonModule,
    DefaultSolutionModalComponent,
    DefaultUserModalComponent,
    ModalComponent,
    ProgressBarComponent,
    RanklistComponent,
  ],
  template: `
    <main class="preview-shell">
      <srk-progress-bar
        [data]="ranklist"
        [td]="timeDiff"
        [live]="true"
        [enableTimeTravel]="true"
        (timeTravel)="handleTimeTravel($event)"
      />
      <div class="preview-spacer"></div>
      <section class="preview-controls" aria-label="Ranklist render options">
        <div class="preview-control-row preview-control-row-primary">
          <label class="preview-field preview-select-field">
            <span>Status preset</span>
            <select
              aria-label="Status preset"
              (change)="statusCellPreset = $any($event.target).value"
            >
              <option
                *ngFor="let option of statusPresetOptions"
                [value]="option.value"
                [selected]="statusCellPreset === option.value"
              >
                {{ option.label }}
              </option>
            </select>
          </label>
          <label class="preview-field preview-select-field">
            <span>Empty status placeholder</span>
            <select
              aria-label="Empty status placeholder"
              (change)="setEmptyStatusPlaceholder($any($event.target).value)"
            >
              <option
                *ngFor="let option of emptyStatusPlaceholderOptions"
                [value]="option.value"
                [selected]="(emptyStatusPlaceholder || '') === option.value"
              >
                {{ option.label }}
              </option>
            </select>
          </label>
          <label class="preview-field preview-select-field">
            <span>User avatar placement</span>
            <select
              aria-label="User avatar placement"
              (change)="userAvatarPlacement = $any($event.target).value"
            >
              <option
                *ngFor="let option of userAvatarPlacementOptions"
                [value]="option.value"
                [selected]="userAvatarPlacement === option.value"
              >
                {{ option.label }}
              </option>
            </select>
          </label>
          <label class="preview-field preview-select-field">
            <span>Language</span>
            <select
              aria-label="Language"
              (change)="language = $any($event.target).value"
            >
              <option
                *ngFor="let option of languageOptions"
                [value]="option.value"
                [selected]="language === option.value"
              >
                {{ option.label }}
              </option>
            </select>
          </label>
          <button type="button" class="preview-action" (click)="useShowcaseOptions()">Showcase</button>
          <button type="button" class="preview-action" (click)="useBaselineOptions()">Baseline</button>
        </div>
        <div class="preview-control-row">
          <label class="preview-field preview-toggle-field">
            <input
              type="checkbox"
              aria-label="Split organization"
              [checked]="splitOrganization"
              (change)="splitOrganization = $any($event.target).checked"
            />
            <span>Split organization</span>
          </label>
          <label class="preview-field preview-toggle-field">
            <input
              type="checkbox"
              aria-label="Custom column titles"
              [checked]="useCustomColumnTitles"
              (change)="useCustomColumnTitles = $any($event.target).checked"
            />
            <span>Custom column titles</span>
          </label>
          <label class="preview-field preview-toggle-field">
            <input
              type="checkbox"
              aria-label="Text status colors"
              [checked]="statusColorAsText"
              (change)="statusColorAsText = $any($event.target).checked"
            />
            <span>Text status colors</span>
          </label>
          <label class="preview-field preview-toggle-field">
            <input
              type="checkbox"
              aria-label="Problem statistics footer"
              [checked]="showProblemStatisticsFooter"
              (change)="showProblemStatisticsFooter = $any($event.target).checked"
            />
            <span>Problem statistics footer</span>
          </label>
          <label class="preview-field preview-toggle-field">
            <input
              type="checkbox"
              aria-label="Dirt column"
              [checked]="showDirtColumn"
              (change)="showDirtColumn = $any($event.target).checked"
            />
            <span>Dirt column</span>
          </label>
          <label class="preview-field preview-toggle-field">
            <input
              type="checkbox"
              aria-label="SE column"
              [checked]="showSEColumn"
              (change)="showSEColumn = $any($event.target).checked"
            />
            <span>SE column</span>
          </label>
          <label class="preview-field preview-toggle-field">
            <input
              type="checkbox"
              aria-label="Row borders"
              [checked]="rowBordered"
              (change)="rowBordered = $any($event.target).checked"
            />
            <span>Row borders</span>
          </label>
          <label class="preview-field preview-toggle-field">
            <input
              type="checkbox"
              aria-label="Column borders"
              [checked]="columnBordered"
              (change)="columnBordered = $any($event.target).checked"
            />
            <span>Column borders</span>
          </label>
        </div>
      </section>
      <div class="preview-spacer"></div>
      <srk-ranklist
        [data]="staticRanklist"
        [theme]="preferredTheme"
        [rowStriped]="true"
        [splitOrganization]="splitOrganization"
        [columnTitles]="useCustomColumnTitles ? demoColumnTitles : undefined"
        [statusCellPreset]="statusCellPreset"
        [statusColorAsText]="statusColorAsText"
        [showProblemStatisticsFooter]="showProblemStatisticsFooter"
        [showDirtColumn]="showDirtColumn"
        [showSEColumn]="showSEColumn"
        [rowBordered]="rowBordered"
        [columnBordered]="columnBordered"
        [emptyStatusPlaceholder]="emptyStatusPlaceholder"
        [userAvatarPlacement]="userAvatarPlacement"
        [languages]="languages"
        (problemClick)="handleProblemClick($event)"
        (solutionClick)="handleSolutionClick($event)"
        (userClick)="handleUserClick($event)"
      />
      <srk-default-user-modal
        [open]="!!activeUserClick"
        [user]="activeUserClick?.user"
        [markers]="staticRanklist.markers"
        [theme]="preferredTheme"
        [languages]="languages"
        (close)="closeUserModal()"
      />
      <srk-modal
        [open]="!!activeProblemClick"
        rootClassName="srk-general-modal-root"
        title="Problem Info"
        [width]="420"
        wrapClassName="srk-problem-modal"
        (close)="closeProblemModal()"
      >
        <div *ngIf="activeProblem">
          <p>Alias: {{ activeProblem.alias || activeProblemIndex + 1 }}</p>
          <p>Title: {{ activeProblemTitle || '-' }}</p>
          <p>Index: {{ activeProblemIndex }}</p>
          <p *ngIf="activeProblem.link">
            Link:
            <a [href]="activeProblem.link" target="_blank" rel="noopener noreferrer">{{ activeProblem.link }}</a>
          </p>
          <p *ngIf="activeProblem.statistics">
            Stats: {{ activeProblem.statistics.accepted }} accepted / {{ activeProblem.statistics.submitted }} submitted
          </p>
        </div>
      </srk-modal>
      <srk-default-solution-modal
        [open]="!!activeSolutionClick"
        [user]="activeSolutionClick?.user"
        [problem]="activeSolutionClick?.problem"
        [problemIndex]="activeSolutionClick?.problemIndex ?? 0"
        [solutions]="activeSolutionClick?.solutions || []"
        [languages]="languages"
        (close)="closeSolutionModal()"
      />
    </main>
  `,
  styles: [`
    :host {
      display: block;
    }

    .preview-spacer {
      height: 20px;
    }
  `],
})
export class AppComponent {
  readonly EnumTheme = EnumTheme;
  readonly preferredTheme = resolvePreferredTheme();
  readonly originalRanklist = demoData as srk.Ranklist;
  readonly sortedSolutions = getSortedCalculatedRawSolutions(this.originalRanklist.rows);
  readonly demoColumnTitles: RanklistColumnTitles = {
    series: (series, index) => (index === 0 ? 'Rank' : series.title || `Series ${index + 1}`),
    organization: 'School',
    user: 'Team',
    score: 'Solved',
    time: 'Penalty',
    dirt: 'Dirt',
    se: 'SE',
  };
  readonly statusPresetOptions: Array<{ value: RanklistStatusCellPreset; label: string }> = [
    { value: 'classic', label: 'Classic' },
    { value: 'detailed', label: 'Detailed' },
    { value: 'minimal', label: 'Minimal' },
    { value: 'compact', label: 'Compact' },
  ];
  readonly emptyStatusPlaceholderOptions = [
    { value: '', label: 'None' },
    { value: '·', label: 'Dot' },
    { value: '-', label: 'Dash' },
  ];
  readonly userAvatarPlacementOptions: Array<{ value: RanklistUserAvatarPlacement; label: string }> = [
    { value: 'user', label: 'User' },
    { value: 'organization', label: 'Organization' },
  ];
  readonly languageOptions: Array<{ value: LanguageOptionValue; label: string }> = [
    { value: 'browser', label: 'Browser' },
    { value: 'zh-CN', label: 'zh-CN' },
    { value: 'en-US', label: 'en-US' },
  ];
  ranklist: srk.Ranklist = this.originalRanklist;
  activeUserClick: UserClickPayload | null = null;
  activeProblemClick: ProblemClickPayload | null = null;
  activeSolutionClick: SolutionClickPayload | null = null;
  splitOrganization = true;
  useCustomColumnTitles = true;
  statusCellPreset: RanklistStatusCellPreset = 'compact';
  statusColorAsText = true;
  showProblemStatisticsFooter = true;
  showDirtColumn = true;
  showSEColumn = true;
  rowBordered = true;
  columnBordered = true;
  emptyStatusPlaceholder: string | null = '·';
  userAvatarPlacement: RanklistUserAvatarPlacement = 'organization';
  language: LanguageOptionValue = 'browser';
  private staticRanklistSource?: srk.Ranklist;
  private staticRanklistLanguage?: LanguageOptionValue;
  private staticRanklistCache?: StaticRanklist;

  get staticRanklist(): StaticRanklist {
    if (
      this.staticRanklistSource !== this.ranklist ||
      this.staticRanklistLanguage !== this.language ||
      !this.staticRanklistCache
    ) {
      this.staticRanklistSource = this.ranklist;
      this.staticRanklistLanguage = this.language;
      this.staticRanklistCache = convertToStaticRanklist(this.ranklist) as StaticRanklist;
    }
    return this.staticRanklistCache;
  }

  get timeDiff() {
    return this.ranklist._now ? Date.now() - new Date(this.ranklist._now).getTime() : 0;
  }

  get languages(): readonly string[] | undefined {
    return this.language === 'browser' ? undefined : [this.language];
  }

  get activeProblem() {
    return this.activeProblemClick?.problem || null;
  }

  get activeProblemIndex() {
    return this.activeProblemClick?.problemIndex ?? 0;
  }

  get activeProblemTitle() {
    return this.activeProblem ? resolveText(this.activeProblem.title, this.languages) : '';
  }

  handleTimeTravel(time: number | null) {
    if (time === null) {
      this.ranklist = this.originalRanklist;
    } else {
      this.ranklist = regenerateRanklistBySolutions(
        this.originalRanklist,
        filterSolutionsUntil(this.sortedSolutions, [time, 'ms']),
      ) as srk.Ranklist;
    }
    this.activeUserClick = null;
    this.activeProblemClick = null;
    this.activeSolutionClick = null;
  }

  handleUserClick(payload: UserClickPayload) {
    this.activeUserClick = payload;
    this.activeProblemClick = null;
    this.activeSolutionClick = null;
  }

  handleProblemClick(payload: ProblemClickPayload) {
    this.activeUserClick = null;
    this.activeProblemClick = payload;
    this.activeSolutionClick = null;
  }

  handleSolutionClick(payload: SolutionClickPayload) {
    this.activeUserClick = null;
    this.activeProblemClick = null;
    this.activeSolutionClick = payload;
  }

  closeUserModal() {
    this.activeUserClick = null;
  }

  closeProblemModal() {
    this.activeProblemClick = null;
  }

  closeSolutionModal() {
    this.activeSolutionClick = null;
  }

  setEmptyStatusPlaceholder(value: string) {
    this.emptyStatusPlaceholder = value || null;
  }

  useBaselineOptions() {
    this.splitOrganization = false;
    this.useCustomColumnTitles = false;
    this.statusCellPreset = 'classic';
    this.statusColorAsText = false;
    this.showProblemStatisticsFooter = false;
    this.showDirtColumn = false;
    this.showSEColumn = false;
    this.rowBordered = false;
    this.columnBordered = false;
    this.emptyStatusPlaceholder = null;
    this.userAvatarPlacement = 'user';
  }

  useShowcaseOptions() {
    this.splitOrganization = true;
    this.useCustomColumnTitles = true;
    this.statusCellPreset = 'compact';
    this.statusColorAsText = true;
    this.showProblemStatisticsFooter = true;
    this.showDirtColumn = true;
    this.showSEColumn = true;
    this.rowBordered = true;
    this.columnBordered = true;
    this.emptyStatusPlaceholder = '·';
    this.userAvatarPlacement = 'organization';
  }
}
