// packages/react/src/Modal.tsx
import classnames from 'classnames';
import React from 'react';
import ReactDOM from 'react-dom';
import {
  MODAL_ANIMATION_DURATION_MS,
  SRK_ANIMATED_MODAL_ROOT_CLASS,
  ensureModalInteractionTracker,
  lockModalBodyScroll,
  registerModalFocusScope,
  resolveModalTransformOrigin,
  unlockModalBodyScroll,
  unregisterModalFocusScope,
} from '@algoux/standard-ranklist-renderer-component-core';

export type ModalCloseReason = 'mask' | 'close-button' | 'escape';

type InteractionPoint = { x: number; y: number };

export interface ModalProps {
  open: boolean;
  title?: React.ReactNode;
  children?: React.ReactNode;
  width?: number;
  rootClassName?: string;
  wrapClassName?: string;
  style?: React.CSSProperties;
  destroyOnClose?: boolean;
  closeOnEsc?: boolean;
  closeOnMaskClick?: boolean;
  onClose?: (event: React.SyntheticEvent | Event, reason: ModalCloseReason) => void;
}

let nextModalId = 0;
const useModalLayoutEffect = typeof window === 'undefined' ? React.useEffect : React.useLayoutEffect;

export function Modal({
  open,
  title,
  children,
  width,
  rootClassName,
  wrapClassName,
  style,
  destroyOnClose = true,
  closeOnEsc = true,
  closeOnMaskClick = true,
  onClose,
}: ModalProps) {
  const titleIdRef = React.useRef(`srk-modal-title-${++nextModalId}`);
  const dialogRef = React.useRef<HTMLDivElement | null>(null);
  const closeTimerRef = React.useRef<number | null>(null);
  const openTimerRef = React.useRef<number | null>(null);
  const focusScopeIdRef = React.useRef<number | null>(null);
  const [isMounted, setIsMounted] = React.useState(open || !destroyOnClose);
  const [animationState, setAnimationState] = React.useState<'pre-open' | 'opening' | 'closing'>(
    open ? 'pre-open' : 'closing',
  );
  const [transformOrigin, setTransformOrigin] = React.useState<InteractionPoint>({ x: 0, y: 0 });

  React.useEffect(() => {
    ensureModalInteractionTracker();
  }, []);

  React.useEffect(() => {
    return () => {
      if (closeTimerRef.current !== null) {
        window.clearTimeout(closeTimerRef.current);
      }
      if (openTimerRef.current !== null) {
        window.clearTimeout(openTimerRef.current);
      }
      unregisterModalFocusScope(focusScopeIdRef.current);
      focusScopeIdRef.current = null;
    };
  }, []);

  React.useEffect(() => {
    if (closeTimerRef.current !== null) {
      window.clearTimeout(closeTimerRef.current);
      closeTimerRef.current = null;
    }
    if (openTimerRef.current !== null) {
      window.clearTimeout(openTimerRef.current);
      openTimerRef.current = null;
    }

    if (open) {
      setIsMounted(true);
      setTransformOrigin({ x: 0, y: 0 });
      setAnimationState('pre-open');
      return;
    }

    setAnimationState('closing');
    if (destroyOnClose && isMounted && typeof window !== 'undefined') {
      closeTimerRef.current = window.setTimeout(() => {
        setIsMounted(false);
      }, MODAL_ANIMATION_DURATION_MS);
    }
  }, [destroyOnClose, isMounted, open]);

  React.useEffect(() => {
    if (!open || !isMounted || animationState !== 'pre-open') {
      return;
    }
    const resolution = resolveModalTransformOrigin(dialogRef.current);
    setTransformOrigin(resolution.origin);
    openTimerRef.current = window.setTimeout(() => {
      setAnimationState('opening');
      openTimerRef.current = null;
    }, 0);

    return () => {
      if (openTimerRef.current !== null) {
        window.clearTimeout(openTimerRef.current);
        openTimerRef.current = null;
      }
    };
  }, [animationState, isMounted, open]);

  const shouldLockBody = open || (destroyOnClose && isMounted);

  React.useEffect(() => {
    if (!shouldLockBody) {
      return;
    }
    lockModalBodyScroll();
    return () => {
      unlockModalBodyScroll();
    };
  }, [shouldLockBody]);

  const handleEscape = React.useCallback(
    (event: KeyboardEvent) => {
      if (closeOnEsc) {
        onClose?.(event, 'escape');
      }
    },
    [closeOnEsc, onClose],
  );

  useModalLayoutEffect(() => {
    if (open && isMounted) {
      focusScopeIdRef.current = registerModalFocusScope(dialogRef.current, {
        onEscape: closeOnEsc ? handleEscape : undefined,
      });
      return;
    }
    if (!open && focusScopeIdRef.current !== null) {
      unregisterModalFocusScope(focusScopeIdRef.current);
      focusScopeIdRef.current = null;
    }
  }, [closeOnEsc, handleEscape, isMounted, open]);

  if (!isMounted && destroyOnClose) {
    return null;
  }

  const dialogStyle: React.CSSProperties = {
    ...style,
    width: width ? `${width}px` : style?.width,
    ['--srk-modal-origin-x' as string]: `${transformOrigin.x}px`,
    ['--srk-modal-origin-y' as string]: `${transformOrigin.y}px`,
    ['--srk-modal-max-width' as string]: width ? `${width}px` : typeof style?.width === 'string' ? style.width : undefined,
  };

  const modalNode = (
    <div
      className={classnames('srk-modal-root', SRK_ANIMATED_MODAL_ROOT_CLASS, 'srk-react-modal-root', rootClassName)}
      data-srk-modal-state={animationState}
    >
      <div className="srk-modal-mask" />
      <div
        className={classnames('srk-modal-wrap', wrapClassName)}
        tabIndex={-1}
        onMouseDown={(event) => {
          if (closeOnMaskClick && event.target === event.currentTarget) {
            onClose?.(event, 'mask');
          }
        }}
      >
        <div
          aria-labelledby={title ? titleIdRef.current : undefined}
          aria-modal="true"
          className="srk-modal"
          data-srk-modal-panel="true"
          ref={dialogRef}
          role="dialog"
          style={dialogStyle}
          tabIndex={-1}
        >
          <div className="srk-modal-content">
            <button
              aria-label="Close"
              className="srk-modal-close"
              type="button"
              onClick={(event) => onClose?.(event, 'close-button')}
            >
              <span className="srk-modal-close-x" />
            </button>
            {title !== undefined && (
              <div className="srk-modal-header">
                <div className="srk-modal-title" id={titleIdRef.current}>
                  {title}
                </div>
              </div>
            )}
            <div className="srk-modal-body">{children}</div>
          </div>
        </div>
      </div>
    </div>
  );

  if (typeof document === 'undefined') {
    return modalNode;
  }

  return ReactDOM.createPortal(modalNode, document.body);
}

// packages/solid/src/Modal.tsx
import type { JSX } from 'solid-js';
import { createEffect, createMemo, createSignal, createUniqueId, on, onCleanup, onMount, Show, untrack } from 'solid-js';
import {
  MODAL_ANIMATION_DURATION_MS,
  SRK_ANIMATED_MODAL_ROOT_CLASS,
  ensureModalInteractionTracker,
  lockModalBodyScroll,
  registerModalFocusScope,
  resolveModalTransformOrigin,
  unlockModalBodyScroll,
  unregisterModalFocusScope,
} from '@algoux/standard-ranklist-renderer-component-core';

export type ModalCloseReason = 'mask' | 'close-button' | 'escape';

export interface ModalProps {
  open: boolean;
  title?: JSX.Element;
  children?: JSX.Element;
  width?: number;
  rootClassName?: string;
  wrapClassName?: string;
  style?: JSX.CSSProperties;
  destroyOnClose?: boolean;
  closeOnEsc?: boolean;
  closeOnMaskClick?: boolean;
  onClose?: (event: MouseEvent | KeyboardEvent, reason: ModalCloseReason) => void;
}

function classNames(...values: Array<string | undefined>) {
  return values.filter(Boolean).join(' ');
}

export function Modal(props: ModalProps) {
  const titleId = createUniqueId();
  const destroyOnClose = () => props.destroyOnClose ?? true;
  const closeOnEsc = () => props.closeOnEsc ?? true;
  const closeOnMaskClick = () => props.closeOnMaskClick ?? true;
  const [isMounted, setIsMounted] = createSignal(props.open || !destroyOnClose());
  const [animationState, setAnimationState] = createSignal<'pre-open' | 'opening' | 'closing'>(
    props.open ? 'pre-open' : 'closing',
  );
  const [transformOrigin, setTransformOrigin] = createSignal({ x: 0, y: 0 });
  let rootRef: HTMLDivElement | undefined;
  let dialogRef: HTMLDivElement | undefined;
  let closeTimer: number | null = null;
  let openTimer: number | null = null;
  let bodyLocked = false;
  let focusScopeId: number | null = null;
  let pendingFocusRegistration = false;
  const shouldRender = createMemo(() => props.open || isMounted() || !destroyOnClose());
  const shouldLockBody = createMemo(() => props.open || (destroyOnClose() && isMounted()));
  const rootClassName = createMemo(() => classNames('srk-modal-root', SRK_ANIMATED_MODAL_ROOT_CLASS, props.rootClassName));
  const baseDialogStyle = createMemo<JSX.CSSProperties>(() => ({
    ...props.style,
    width: props.width ? `${props.width}px` : props.style?.width,
    maxWidth: props.style?.maxWidth,
  }));

  const clearTimers = () => {
    if (closeTimer !== null) {
      window.clearTimeout(closeTimer);
      closeTimer = null;
    }
    if (openTimer !== null) {
      window.clearTimeout(openTimer);
      openTimer = null;
    }
  };

  function handleEscape(event: KeyboardEvent) {
    if (props.open && closeOnEsc()) {
      props.onClose?.(event, 'escape');
    }
  }

  const registerFocusScope = () => {
    if (!props.open || !dialogRef || focusScopeId !== null) {
      return;
    }

    if (!dialogRef.isConnected) {
      if (!pendingFocusRegistration) {
        pendingFocusRegistration = true;
        queueMicrotask(() => {
          pendingFocusRegistration = false;
          registerFocusScope();
        });
      }
      return;
    }

    focusScopeId = registerModalFocusScope(dialogRef, {
      onEscape: handleEscape,
    });
  };

  onMount(() => {
    registerFocusScope();
  });

  createEffect(() => {
    ensureModalInteractionTracker();
  });

  onCleanup(() => {
    clearTimers();
    unregisterModalFocusScope(focusScopeId);
    focusScopeId = null;
  });

  createEffect(
    on(
      () => props.open,
      (open) => {
        const destroy = destroyOnClose();

        clearTimers();

        if (open) {
          setIsMounted(true);
          setTransformOrigin({ x: 0, y: 0 });
          setAnimationState('pre-open');

          if (typeof window !== 'undefined') {
            openTimer = window.setTimeout(() => {
              if (!props.open || animationState() !== 'pre-open') {
                openTimer = null;
                return;
              }
              const resolution = resolveModalTransformOrigin(dialogRef || null);
              setTransformOrigin(resolution.origin);
              setAnimationState('opening');
              openTimer = null;
            }, 0);
          }
          return;
        }

        if (focusScopeId !== null) {
          unregisterModalFocusScope(focusScopeId);
          focusScopeId = null;
        }
        setAnimationState('closing');
        if (!destroy) {
          setIsMounted(true);
          return;
        }

        if (untrack(isMounted) && typeof window !== 'undefined') {
          closeTimer = window.setTimeout(() => {
            if (bodyLocked) {
              unlockModalBodyScroll();
              bodyLocked = false;
            }
            rootRef?.remove();
            setIsMounted(false);
            closeTimer = null;
          }, MODAL_ANIMATION_DURATION_MS);
        }
      },
      { defer: false },
    ),
  );

  createEffect(
    on(
      shouldLockBody,
      (lock) => {
        if (lock && !bodyLocked) {
          lockModalBodyScroll();
          bodyLocked = true;
          return;
        }

        if (!lock && bodyLocked) {
          unlockModalBodyScroll();
          bodyLocked = false;
          return;
        }
      },
      { defer: false },
    ),
  );

  onCleanup(() => {
    if (bodyLocked) {
      unlockModalBodyScroll();
      bodyLocked = false;
    }
    unregisterModalFocusScope(focusScopeId);
    focusScopeId = null;
  });

  createEffect(() => {
    if (props.open && shouldRender()) {
      registerFocusScope();
    }
  });

  createEffect(() => {
    const width = props.width ? `${props.width}px` : typeof props.style?.width === 'string' ? props.style.width : null;
    const originX = `${transformOrigin().x}px`;
    const originY = `${transformOrigin().y}px`;
    const state = animationState();
    const root = rootRef;
    const dialog = dialogRef;

    if (root) {
      root.setAttribute('data-srk-modal-state', state);
    }

    if (!dialog) {
      return;
    }

    if (width) {
      dialog.style.width = width;
      dialog.style.setProperty('--srk-modal-max-width', width);
    } else {
      dialog.style.removeProperty('width');
      dialog.style.removeProperty('--srk-modal-max-width');
    }

    dialog.style.setProperty('--srk-modal-origin-x', originX);
    dialog.style.setProperty('--srk-modal-origin-y', originY);
  });

  const content = () => (
    <div
      class={rootClassName()}
      data-srk-modal-state={animationState()}
      ref={rootRef}
    >
      <div class="srk-modal-mask" />
      <div
        class={classNames('srk-modal-wrap', props.wrapClassName)}
        tabIndex={-1}
        onMouseDown={(event) => {
          if (closeOnMaskClick() && event.target === event.currentTarget) {
            props.onClose?.(event, 'mask');
          }
        }}
      >
        <div
          aria-labelledby={props.title !== undefined ? titleId : undefined}
          aria-modal="true"
          class="srk-modal"
          data-srk-modal-panel="true"
          role="dialog"
          ref={(element) => {
            dialogRef = element;
            registerFocusScope();
          }}
          style={baseDialogStyle()}
          tabIndex={-1}
        >
          <div class="srk-modal-content">
            <button
              aria-label="Close"
              class="srk-modal-close"
              type="button"
              onClick={(event) => props.onClose?.(event, 'close-button')}
            >
              <span class="srk-modal-close-x" />
            </button>
            <Show when={props.title !== undefined}>
              <div class="srk-modal-header">
                <div class="srk-modal-title" id={titleId}>
                  {props.title}
                </div>
              </div>
            </Show>
            <div class="srk-modal-body">{props.children}</div>
          </div>
        </div>
      </div>
    </div>
  );

  return <Show when={shouldRender()}>{content}</Show>;
}
