// packages/angular/src/lib/progress/progress-bar.component.ts
import type * as srk from '@algoux/standard-ranklist';
import { CommonModule } from '@angular/common';
import {
  Component,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
} from '@angular/core';
import { secToTimeStr } from '@algoux/standard-ranklist-utils';
import {
  getProgressDurationMinutes,
  getProgressMaxAvailableMinutes,
  getProgressMetrics,
  isProgressEnded,
} from './progress-utils';

@Component({
  selector: 'srk-progress-bar',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="srk-progress-bar-container">
      <div class="srk-progress-bar">
        <div class="srk-progress-bar-body">
          <div
            class="srk-progress-bar-segment srk-progress-bar-normal"
            [style.width.%]="progressMetrics().frozenBreakpoint * 100"
          >
            <div class="srk-progress-bar-fill" [style.width.%]="progressMetrics().normalInnerPercent"></div>
          </div>
          <div
            class="srk-progress-bar-segment srk-progress-bar-frozen"
            [style.width.%]="(1 - progressMetrics().frozenBreakpoint) * 100"
          >
            <div class="srk-progress-bar-fill" [style.width.%]="progressMetrics().frozenInnerPercent"></div>
          </div>
        </div>
        <div
          *ngIf="enableTimeTravel && progressMetrics().supportRegen"
          class="srk-progress-slider-layer"
        >
          <div
            *ngIf="timeTravelIsChanging"
            class="srk-progress-slider-tooltip"
            [style.left.%]="durationMinutes() ? (timeTravelCurrentValue / durationMinutes()) * 100 : 0"
          >
            {{ timeLabel(timeTravelCurrentValue) }}
          </div>
          <input
            aria-label="Time Travel"
            class="srk-progress-slider"
            min="0"
            step="1"
            type="range"
            [max]="durationMinutes()"
            [title]="timeLabel(timeTravelCurrentValue)"
            [value]="timeTravelCurrentValue"
            (blur)="commitTimeTravel()"
            (input)="updateTimeTravelValue($event)"
            (keydown)="beginTimeTravel()"
            (keyup)="commitTimeTravel()"
            (mousedown)="beginTimeTravel()"
            (mouseup)="commitTimeTravel()"
            (touchend)="commitTimeTravel()"
            (touchstart)="beginTimeTravel()"
          />
        </div>
      </div>
      <div class="srk-progress-secondary-area">
        <div
          class="srk-progress-secondary-area-left"
          [style.display]="live || inTimeMachine ? '' : 'none'"
        >
          Elapsed: {{ secToTimeStr(progressMetrics().elapsed / 1000) }}
        </div>
        <div class="srk-progress-secondary-area-center">
          <div *ngIf="inTimeMachine" class="srk-progress-time-machine-status">
            <div class="srk-progress-time-machine-text">Time Travel Mode</div>
          </div>
          <div *ngIf="!inTimeMachine && live && !isEnded()" class="srk-progress-live-text">
            Live
          </div>
          <div *ngIf="!inTimeMachine && (!live || isEnded())" style="visibility: hidden">
            SRK
          </div>
        </div>
        <div
          class="srk-progress-secondary-area-right"
          [style.display]="live || inTimeMachine ? '' : 'none'"
        >
          Remaining: {{ secToTimeStr(progressMetrics().remaining / 1000) }}
        </div>
      </div>
    </div>
  `,
})
export class ProgressBarComponent implements OnInit, OnDestroy {
  @Input({ required: true }) data!: srk.Ranklist;
  @Input() enableTimeTravel = false;
  @Input() live = false;
  @Input() td = 0;

  @Output() timeTravel = new EventEmitter<number | null>();

  localTime = Date.now();
  inTimeMachine = false;
  timeTravelIsChanging = false;
  timeTravelCurrentValue = 0;
  timeTravelValue: number | null = null;

  private liveInterval?: number;

  ngOnInit() {
    this.timeTravelCurrentValue = this.maxAvailableMinutes();
    if (this.live) {
      this.liveInterval = window.setInterval(() => this.handleProgressTimer(), 1000);
    }
  }

  ngOnDestroy() {
    if (this.liveInterval) {
      window.clearInterval(this.liveInterval);
    }
  }

  secToTimeStr(seconds: number) {
    return secToTimeStr(Math.round(seconds));
  }

  timeLabel(minutes: number) {
    return secToTimeStr(minutes * 60);
  }

  durationMinutes() {
    return getProgressDurationMinutes(this.data.contest);
  }

  maxAvailableMinutes() {
    return getProgressMaxAvailableMinutes(this.data.contest, this.localTime, this.td);
  }

  isEnded() {
    return isProgressEnded(this.data.contest, this.localTime, this.td);
  }

  progressMetrics() {
    return getProgressMetrics(
      this.data,
      this.localTime,
      this.td,
      this.timeTravelCurrentValue,
      this.inTimeMachine,
    );
  }

  beginTimeTravel() {
    this.timeTravelIsChanging = true;
    this.inTimeMachine = true;
  }

  updateTimeTravelValue(event: Event) {
    this.timeTravelCurrentValue = Number((event.target as HTMLInputElement).value);
  }

  commitTimeTravel() {
    if (this.timeTravelIsChanging) {
      this.handleTimeTravelChange(this.timeTravelCurrentValue);
    }
  }

  private handleProgressTimer() {
    this.localTime = Date.now();
    if (this.isEnded() && this.liveInterval) {
      window.clearInterval(this.liveInterval);
    }
    if (!this.timeTravelIsChanging && this.timeTravelValue === null) {
      this.timeTravelCurrentValue = this.maxAvailableMinutes();
    }
  }

  private handleTimeTravelChange(value: number) {
    const exited = value >= this.durationMinutes() || value >= this.maxAvailableMinutes();
    this.timeTravel.emit(exited ? null : value * 60 * 1000);
    this.inTimeMachine = !exited;
    this.timeTravelValue = exited ? null : value * 60 * 1000;
    this.timeTravelIsChanging = false;
  }
}

// packages/vue/src/progress/ProgressBar.vue
<template>
  <div class="srk-progress-bar-container">
    <div class="srk-progress-bar">
      <div class="srk-progress-bar-body">
        <div
          class="srk-progress-bar-segment srk-progress-bar-normal"
          :style="{ width: `${progressMetrics.frozenBreakpoint * 100}%` }"
        >
          <div class="srk-progress-bar-fill" :style="{ width: `${progressMetrics.normalInnerPercent}%` }"></div>
        </div>
        <div
          class="srk-progress-bar-segment srk-progress-bar-frozen"
          :style="{ width: `${(1 - progressMetrics.frozenBreakpoint) * 100}%` }"
        >
          <div class="srk-progress-bar-fill" :style="{ width: `${progressMetrics.frozenInnerPercent}%` }"></div>
        </div>
      </div>
      <div v-if="enableTimeTravel && progressMetrics.supportRegen" class="srk-progress-slider-layer">
        <div
          v-if="timeTravelIsChanging"
          class="srk-progress-slider-tooltip"
          :style="{ left: `${durationMinutes ? (timeTravelCurrentValue / durationMinutes) * 100 : 0}%` }"
        >
          {{ secToTimeStr(timeTravelCurrentValue * 60) }}
        </div>
        <input
          v-model.number="timeTravelCurrentValue"
          aria-label="Time Travel"
          class="srk-progress-slider"
          :max="durationMinutes"
          min="0"
          step="1"
          :title="secToTimeStr(timeTravelCurrentValue * 60)"
          type="range"
          @blur="commitTimeTravel"
          @keydown="beginTimeTravel"
          @keyup="commitTimeTravel"
          @mousedown="beginTimeTravel"
          @mouseup="commitTimeTravel"
          @touchend="commitTimeTravel"
          @touchstart="beginTimeTravel"
        />
      </div>
    </div>
    <div class="srk-progress-secondary-area">
      <div class="srk-progress-secondary-area-left" :style="live || inTimeMachine ? {} : { display: 'none' }">
        Elapsed: {{ secToTimeStr(Math.round(progressMetrics.elapsed / 1000)) }}
      </div>
      <div class="srk-progress-secondary-area-center">
        <div v-if="inTimeMachine" class="srk-progress-time-machine-status">
          <div class="srk-progress-time-machine-text">Time Travel Mode</div>
        </div>
        <div v-else-if="live && !isEnded" class="srk-progress-live-text">Live</div>
        <div v-else style="visibility: hidden">SRK</div>
      </div>
      <div class="srk-progress-secondary-area-right" :style="live || inTimeMachine ? {} : { display: 'none' }">
        Remaining: {{ secToTimeStr(Math.round(progressMetrics.remaining / 1000)) }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type * as srk from '@algoux/standard-ranklist';
import { secToTimeStr } from '@algoux/standard-ranklist-utils';
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import {
  getProgressDurationMinutes,
  getProgressMaxAvailableMinutes,
  getProgressMetrics,
  isProgressEnded,
} from '@algoux/standard-ranklist-renderer-component-core';

const props = withDefaults(
  defineProps<{
    data: srk.Ranklist;
    enableTimeTravel?: boolean;
    live?: boolean;
    td?: number;
  }>(),
  {
    enableTimeTravel: false,
    live: false,
    td: 0,
  },
);

const emit = defineEmits<{
  timeTravel: [time: number | null];
}>();

const localTime = ref(Date.now());
const inTimeMachine = ref(false);
const timeTravelIsChanging = ref(false);
const timeTravelCurrentValue = ref(getProgressMaxAvailableMinutes(props.data.contest, localTime.value, props.td));
const timeTravelValue = ref<number | null>(null);
let liveInterval: number | undefined;

const durationMinutes = computed(() => getProgressDurationMinutes(props.data.contest));
const maxAvailableMinutes = computed(() => getProgressMaxAvailableMinutes(props.data.contest, localTime.value, props.td));
const isEnded = computed(() => isProgressEnded(props.data.contest, localTime.value, props.td));
const progressMetrics = computed(() =>
  getProgressMetrics(props.data, localTime.value, props.td, timeTravelCurrentValue.value, inTimeMachine.value),
);

function handleProgressTimer() {
  localTime.value = Date.now();
  if (isEnded.value && liveInterval !== undefined) {
    window.clearInterval(liveInterval);
    liveInterval = undefined;
  }
}

function syncLiveInterval(live: boolean) {
  if (typeof window === 'undefined') {
    return;
  }
  if (live && liveInterval === undefined) {
    liveInterval = window.setInterval(handleProgressTimer, 1000);
  }
  if (!live && liveInterval !== undefined) {
    window.clearInterval(liveInterval);
    liveInterval = undefined;
  }
}

function handleTimeTravelChange(value: number) {
  const exited = value >= durationMinutes.value || value >= maxAvailableMinutes.value;
  emit('timeTravel', exited ? null : value * 60 * 1000);
  inTimeMachine.value = !exited;
  timeTravelValue.value = exited ? null : value * 60 * 1000;
  timeTravelIsChanging.value = false;
}

function beginTimeTravel() {
  timeTravelIsChanging.value = true;
  inTimeMachine.value = true;
}

function commitTimeTravel() {
  if (timeTravelIsChanging.value) {
    handleTimeTravelChange(timeTravelCurrentValue.value);
  }
}

watch(maxAvailableMinutes, (value) => {
  if (!timeTravelIsChanging.value && timeTravelValue.value === null) {
    timeTravelCurrentValue.value = value;
  }
});

watch(
  () => props.live,
  (live) => syncLiveInterval(live),
  { immediate: true },
);

watch(
  () => props.data.contest.title,
  () => {
    timeTravelIsChanging.value = false;
    timeTravelCurrentValue.value = maxAvailableMinutes.value;
    timeTravelValue.value = null;
    inTimeMachine.value = false;
    emit('timeTravel', null);
  },
);

onBeforeUnmount(() => {
  if (liveInterval !== undefined) {
    window.clearInterval(liveInterval);
    liveInterval = undefined;
  }
});
</script>
