// packages/vue/src/modal/Modal.vue
<template>
  <div v-if="shouldRender" :class="rootClasses" :data-srk-modal-state="animationState">
    <div class="srk-modal-mask"></div>
    <div
      class="srk-modal-wrap"
      :class="wrapClassName"
      tabindex="-1"
      @mousedown="handleMaskMouseDown"
    >
      <div
        class="srk-modal"
        role="dialog"
        aria-modal="true"
        :aria-labelledby="title ? titleId : undefined"
        data-srk-modal-panel="true"
        tabindex="-1"
        ref="dialogRef"
        :style="dialogStyle"
      >
        <div class="srk-modal-content">
          <button aria-label="Close" class="srk-modal-close" type="button" @click="requestClose('close-button')">
            <span class="srk-modal-close-x"></span>
          </button>
          <div v-if="title !== undefined" class="srk-modal-header">
            <div :id="titleId" class="srk-modal-title">{{ title }}</div>
          </div>
          <div class="srk-modal-body">
            <slot></slot>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { CSSProperties } from 'vue';
import {
  MODAL_ANIMATION_DURATION_MS,
  SRK_ANIMATED_MODAL_ROOT_CLASS,
  ensureModalInteractionTracker,
  lockModalBodyScroll,
  registerModalFocusScope,
  resolveModalTransformOrigin,
  unlockModalBodyScroll,
  unregisterModalFocusScope,
} from '@algoux/standard-ranklist-renderer-component-core';
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch, watchEffect } from 'vue';

let nextModalId = 0;

const props = withDefaults(
  defineProps<{
    open: boolean;
    title?: string;
    width?: number;
    rootClassName?: string;
    wrapClassName?: string;
    style?: CSSProperties;
    destroyOnClose?: boolean;
    closeOnEsc?: boolean;
    closeOnMaskClick?: boolean;
  }>(),
  {
    destroyOnClose: true,
    closeOnEsc: true,
    closeOnMaskClick: true,
  },
);

const emit = defineEmits<{
  close: [reason: 'mask' | 'close-button' | 'escape'];
  'update:open': [open: boolean];
}>();

const titleId = `srk-vue-modal-title-${++nextModalId}`;
const dialogRef = ref<HTMLDivElement | null>(null);
const isMounted = ref(props.open || !props.destroyOnClose);
const animationState = ref<'pre-open' | 'opening' | 'closing'>(props.open ? 'pre-open' : 'closing');
const transformOrigin = ref({ x: 0, y: 0 });
let closeTimer: number | null = null;
let openTimer: number | null = null;
let focusScopeId: number | null = null;

const shouldRender = computed(() => isMounted.value || !props.destroyOnClose);
const rootClasses = computed(() => ['srk-modal-root', SRK_ANIMATED_MODAL_ROOT_CLASS, props.rootClassName].filter(Boolean));
const shouldLockBody = computed(() => props.open || (props.destroyOnClose && isMounted.value));
const dialogStyle = computed(() => ({
  ...props.style,
  width: props.width ? `${props.width}px` : props.style?.width,
  ['--srk-modal-origin-x' as string]: `${transformOrigin.value.x}px`,
  ['--srk-modal-origin-y' as string]: `${transformOrigin.value.y}px`,
  ['--srk-modal-max-width' as string]: props.width
    ? `${props.width}px`
    : typeof props.style?.width === 'string'
      ? props.style.width
      : undefined,
}));

function clearTimers() {
  if (typeof window === 'undefined') {
    closeTimer = null;
    openTimer = null;
    return;
  }
  if (closeTimer !== null) {
    window.clearTimeout(closeTimer);
    closeTimer = null;
  }
  if (openTimer !== null) {
    window.clearTimeout(openTimer);
    openTimer = null;
  }
}

async function queueOpenAnimation() {
  await nextTick();
  if (typeof window === 'undefined' || !props.open || !isMounted.value || animationState.value !== 'pre-open') {
    return;
  }
  registerFocusScope();
  const resolution = resolveModalTransformOrigin(dialogRef.value);
  transformOrigin.value = resolution.origin;
  openTimer = window.setTimeout(() => {
    animationState.value = 'opening';
    openTimer = null;
  }, 0);
}

function registerFocusScope() {
  const nextFocusScopeId = registerModalFocusScope(dialogRef.value, {
    onEscape: handleEscape,
  });
  if (focusScopeId === null) {
    focusScopeId = nextFocusScopeId;
  }
}

function releaseFocusScope() {
  if (focusScopeId !== null) {
    unregisterModalFocusScope(focusScopeId);
    focusScopeId = null;
  }
}

function requestClose(reason: 'mask' | 'close-button' | 'escape') {
  emit('update:open', false);
  emit('close', reason);
}

function handleMaskMouseDown(event: MouseEvent) {
  if (props.closeOnMaskClick && event.target === event.currentTarget) {
    requestClose('mask');
  }
}

function handleEscape(event: KeyboardEvent) {
  if (props.open && props.closeOnEsc) {
    requestClose('escape');
  }
}

watch(
  () => props.open,
  async (open) => {
    clearTimers();

    if (open) {
      isMounted.value = true;
      transformOrigin.value = { x: 0, y: 0 };
      animationState.value = 'pre-open';
      await queueOpenAnimation();
      return;
    }

    releaseFocusScope();
    animationState.value = 'closing';
    if (!props.destroyOnClose) {
      isMounted.value = true;
      return;
    }

    if (isMounted.value && typeof window !== 'undefined') {
      closeTimer = window.setTimeout(() => {
        isMounted.value = false;
        closeTimer = null;
      }, MODAL_ANIMATION_DURATION_MS);
    }
  },
  { immediate: true },
);

watchEffect((onCleanup) => {
  if (!shouldLockBody.value) {
    return;
  }
  lockModalBodyScroll();
  onCleanup(() => {
    unlockModalBodyScroll();
  });
});

onMounted(() => {
  ensureModalInteractionTracker();
  if (props.open) {
    registerFocusScope();
  }
});

onBeforeUnmount(() => {
  clearTimers();
  releaseFocusScope();
});
</script>

// packages/angular/src/lib/modal/modal.component.ts
import { CommonModule } from '@angular/common';
import {
  AfterViewChecked,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  SimpleChanges,
  ViewChild,
} from '@angular/core';
import {
  MODAL_ANIMATION_DURATION_MS,
  SRK_ANIMATED_MODAL_ROOT_CLASS,
  ensureModalInteractionTracker,
  lockModalBodyScroll,
  registerModalFocusScope,
  resolveModalTransformOrigin,
  unlockModalBodyScroll,
  unregisterModalFocusScope,
} from './modal-interactions';

export type ModalCloseReason = 'mask' | 'close-button' | 'escape';

@Component({
  selector: 'srk-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div *ngIf="shouldRender()" class="srk-modal-root" [ngClass]="rootClasses()" [attr.data-srk-modal-state]="animationState">
      <div class="srk-modal-mask"></div>
      <div
        class="srk-modal-wrap"
        [ngClass]="wrapClassName"
        tabindex="-1"
        (mousedown)="handleMaskMouseDown($event)"
      >
        <div
          #dialog
          class="srk-modal"
          role="dialog"
          aria-modal="true"
          [attr.aria-label]="title || undefined"
          data-srk-modal-panel="true"
          tabindex="-1"
          [ngStyle]="dialogStyle()"
        >
          <div class="srk-modal-content">
            <button
              aria-label="Close"
              class="srk-modal-close"
              type="button"
              (click)="requestClose('close-button')"
            >
              <span class="srk-modal-close-x"></span>
            </button>
            <div *ngIf="title !== undefined" class="srk-modal-header">
              <div class="srk-modal-title">{{ title }}</div>
            </div>
            <div class="srk-modal-body">
              <ng-content />
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class ModalComponent implements AfterViewChecked, OnChanges, OnDestroy {
  @Input() open = false;
  @Input() title?: string;
  @Input() width?: number;
  @Input() rootClassName?: string;
  @Input() wrapClassName?: string;
  @Input() destroyOnClose = true;
  @Input() closeOnEsc = true;
  @Input() closeOnMaskClick = true;
  @Input() panelStyle: Record<string, string | number> = {};

  @Output() openChange = new EventEmitter<boolean>();
  @Output() close = new EventEmitter<ModalCloseReason>();

  @ViewChild('dialog') dialogRef?: ElementRef<HTMLDivElement>;

  isMounted = this.open || !this.destroyOnClose;
  animationState: 'pre-open' | 'opening' | 'closing' = this.open ? 'pre-open' : 'closing';
  transformOrigin = { x: 0, y: 0 };
  private closeTimer: number | null = null;
  private openTimer: number | null = null;
  private bodyScrollLocked = false;
  private focusScopeId: number | null = null;

  constructor() {
    if (typeof document !== 'undefined') {
      ensureModalInteractionTracker();
    }
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['open'] || changes['destroyOnClose']) {
      this.syncOpenState();
    }
  }

  ngAfterViewChecked() {
    if (this.open) {
      this.registerFocusScope();
    }
  }

  ngOnDestroy() {
    this.clearTimers();
    this.releaseFocusScope();
    if (this.bodyScrollLocked) {
      unlockModalBodyScroll();
      this.bodyScrollLocked = false;
    }
  }

  handleEscape(event?: KeyboardEvent) {
    if (this.open && this.closeOnEsc) {
      this.requestClose('escape');
    }
  }

  handleMaskMouseDown(event: MouseEvent) {
    if (this.closeOnMaskClick && event.target === event.currentTarget) {
      this.requestClose('mask');
    }
  }

  requestClose(reason: ModalCloseReason) {
    this.openChange.emit(false);
    this.close.emit(reason);
  }

  shouldRender() {
    return this.isMounted || !this.destroyOnClose;
  }

  rootClasses() {
    return [SRK_ANIMATED_MODAL_ROOT_CLASS, this.rootClassName].filter(Boolean);
  }

  dialogStyle() {
    return {
      ...this.panelStyle,
      width: this.width ? `${this.width}px` : this.panelStyle?.['width'],
      '--srk-modal-origin-x': `${this.transformOrigin.x}px`,
      '--srk-modal-origin-y': `${this.transformOrigin.y}px`,
      '--srk-modal-max-width': this.width
        ? `${this.width}px`
        : typeof this.panelStyle?.['width'] === 'string'
          ? this.panelStyle['width']
          : undefined,
    };
  }

  private clearTimers() {
    if (this.closeTimer !== null) {
      window.clearTimeout(this.closeTimer);
      this.closeTimer = null;
    }
    if (this.openTimer !== null) {
      window.clearTimeout(this.openTimer);
      this.openTimer = null;
    }
  }

  private syncOpenState() {
    this.clearTimers();

    if (this.open) {
      this.isMounted = true;
      this.transformOrigin = { x: 0, y: 0 };
      this.animationState = 'pre-open';
      if (typeof window !== 'undefined') {
        this.openTimer = window.setTimeout(() => {
          this.registerFocusScope();
          const resolution = resolveModalTransformOrigin(this.dialogRef?.nativeElement || null);
          this.transformOrigin = resolution.origin;
          this.animationState = 'opening';
          this.openTimer = null;
        }, 0);
      }
    } else {
      this.releaseFocusScope();
      this.animationState = 'closing';
      if (!this.destroyOnClose) {
        this.isMounted = true;
      } else if (this.isMounted && typeof window !== 'undefined') {
        this.closeTimer = window.setTimeout(() => {
          this.isMounted = false;
          this.updateBodyScrollLock();
          this.closeTimer = null;
        }, MODAL_ANIMATION_DURATION_MS);
      }
    }

    this.updateBodyScrollLock();
  }

  private updateBodyScrollLock() {
    const shouldLock = this.open || (this.destroyOnClose && this.isMounted);
    if (shouldLock && !this.bodyScrollLocked) {
      lockModalBodyScroll();
      this.bodyScrollLocked = true;
      return;
    }
    if (!shouldLock && this.bodyScrollLocked) {
      unlockModalBodyScroll();
      this.bodyScrollLocked = false;
    }
  }

  private registerFocusScope() {
    const nextFocusScopeId = registerModalFocusScope(this.dialogRef?.nativeElement || null, {
      onEscape: this.closeOnEsc ? (event) => this.handleEscape(event) : undefined,
    });
    if (this.focusScopeId === null) {
      this.focusScopeId = nextFocusScopeId;
    }
  }

  private releaseFocusScope() {
    if (this.focusScopeId !== null) {
      unregisterModalFocusScope(this.focusScopeId);
      this.focusScopeId = null;
    }
  }
}
